### ISSUE TITLE
Can not get conventional connection string (SQLCONNSTR_) when using prefix

### ISSUE THREAD

**Issue by rechkalov** [dotnet/extensions#1306]
### Describe the bug
Can not use "SQLCONNSTR_" and custom app prefix at the same time (for example "MYAPP_SQLCONNSTR_MYDB")

### To Reproduce
1. Using version '2.2.0' of package 'Microsoft.Extensions.Configuration.EnvironmentVariables'
2. Run this code:
```c#
Environment.SetEnvironmentVariable("MYAPP_SQLCONNSTR_MYDB", "1111");
Environment.SetEnvironmentVariable("SQLCONNSTR_MYDB", "2222");
var configuration = new ConfigurationBuilder().AddEnvironmentVariables("MYAPP_").Build();

var result = configuration.AsEnumerable().ToArray();
```

result contains only one item: [SQLCONNSTR_MYDB, 1111]

```c#
Environment.SetEnvironmentVariable("MYAPP_SQLCONNSTR_MYDB", "1111");
Environment.SetEnvironmentVariable("SQLCONNSTR_MYDB", "2222");
var configuration = new ConfigurationBuilder().AddEnvironmentVariables().Build();

var result = configuration.AsEnumerable().ToArray();
```

and now result contains environment variables plus mapped connection strings: [ConnectionStrings:MYDB_ProviderName, System.Data.SqlClient], [ConnectionStrings:MYDB, 2222]

### Expected behavior
Behavior should be similar in both cases.

### Additional context
It seems that problem is in ```EnvironmentVariablesConfigurationProvider```: 
```
var filteredEnvVariables = envVariables
    .Cast<DictionaryEntry>()
    .SelectMany(AzureEnvToAppEnv)
    .Where(entry => ((string)entry.Key).StartsWith(_prefix, StringComparison.OrdinalIgnoreCase));
```

must be replased with 
```
var filteredEnvVariables = envVariables
    .Cast<DictionaryEntry>()
    .Where(entry => ((string)entry.Key).StartsWith(_prefix, StringComparison.OrdinalIgnoreCase))
    .Select(entry => new DictionaryEntry(((string)entry.Key).Substring(_prefix.Length), entry.Value))
    .SelectMany(AzureEnvToAppEnv);
```

or something like this (filter first, then map)

**Comment by declspec** [comment]
To piggy-back on this issue, part of the problem is the following test:

https://github.com/aspnet/Extensions/blob/192abfd/src/Configuration/Config.EnvironmentVariables/test/EnvironmentVariablesTest.cs#L94

This implies that the prefix check should happen AFTER the 'magic' mapping of Azure Connection strings into `ConnectionString:*` entries. This violates how the rest of the class behaves, which is to just check if the environment variable is prefixed with the user-defined value or not. 

For example, as @rechkalov thought, `MYAPP_SQLCONNSTR_MYDB` should be filtered to `SQLCONNSTR_MYDB` when `prefix=MYAPP_`, the resulting value should then be run through the 'magic' mapping and get translated into `ConnectionStrings:MYDB'.

In practice, at least through the Azure Portal UI, there is no way to specify such a prefix in the 'Connection Strings' section so I can see why it may not have been handled that way. However the current implementation is essentially the worst of both worlds as unless your 'prefix' value is literally `ConnectionStrings:` like in the test, there is no way for it to NOT get removed, i.e. `SQLCONNSTR_MYDB -> ConnectionStrings:MYDB -> not included as it does not start with 'MYAPP_`
