### ISSUE TITLE
ObjectPool should support provisioning diagnostics 

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/extensions#1439]
We're using object pool for pooling some per request context objects.
 
We currently deploy this with a custom policy that tracks diagnostics about amount of times Create was called, once that's over the pool size we start logging debug messages mentioning the policy was forced to create ephemeral objects and that the pool might be too small.

I'd expect it to be very helpful to have this built into the default pool instead. either as a diagnostic source kind of thing or just via ILogger.

While we're at it, have a DefaultObjectPool that's sealed, saves some virtual dispatch overhead. DefaultObjectPool itself is useless to inherit outside the assembly anyway as everything you would want is `private protected`.

I'm happy to submit a PR!

**Comment by gfoidl** [comment]
> have a DefaultObjectPool that's sealed

Due https://github.com/aspnet/Extensions/blob/81eeb6f93d967b03f1f9406c9c85f3b189e4e1e6/src/ObjectPool/src/DisposableObjectPool.cs#L10 not doable in a easy way.

> have this built into the default pool instead

Do mean built into a `IPooledObjectPolicy<T>` that is provided by default or into the `DefaultObjectPool<T>`? For me it would belong into the policy (as you do already).

**Comment by NinoFloris** [comment]
It's not great in the policy because you miss all context and have to manage your own counts. If we could pass through those numbers I'd be happy too

**Comment by anurse** [comment]
> I'd expect it to be very helpful to have this built into the default pool instead.

It certainly seems useful. I'd strongly suggest we use [`EventCounter`](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Tracing/documentation/EventCounterTutorial.md) for some of these metrics. It also seems like this would be a good place for [`EventSource`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.tracing.eventsource?view=netframework-4.8) tracing since it's not always feasible to get an `ILogger` in to place.

> While we're at it, have a DefaultObjectPool that's sealed, saves some virtual dispatch overhead.

Do you have performance numbers to show this benefit? To be honest, it doesn't seem like this is a high-priority change for the framework object pool to add.

I'm putting this on the backlog because we don't really have any plans to work on this area in 3.0. Happy to consider PRs and discuss ideas here though.
