### ISSUE TITLE
DependencyInjection and IAsyncDisposable

### ISSUE THREAD

**Issue by seesharper** [dotnet/extensions#1751]
Hi. I am the author of LightInject and was wondering if there is something we should be aware of with regards to `AsyncDisposable`. I see that tests has been added here.

https://github.com/aspnet/Extensions/blob/master/src/DependencyInjection/DI/test/ServiceProviderContainerTests.AsyncDisposable.cs

Although there seems to be no sign of `AsyncDisposable` in the specification tests we as adapter developers use to confirm compatibility? 

@davidfowl. Anything external DI developers needs to know about? 😀

**Comment by pakrym** [comment]
AsyncDisposable implementation is optional, hosting would call `DisposeAsync` if the container implements `IAsyncDisposable` or `Dispose` if it only implements IDisposable.  That's why specification doesn't require it.

**Comment by anurse** [comment]
Closing inactive discussion thread.

---

##### Note: Inactive closed issues are locked after 30 days since we don't triage closed issues and new comments tend to be lost. Feel free to post a new issue if this issue is locked and you have further questions/discussions. See [our issue management policies](https://github.com/dotnet/aspnetcore/blob/master/docs/IssueManagementPolicies.md) for more details.
