### ISSUE TITLE
Scopes should not appear in logs after they are disposed.

### ISSUE THREAD

**Issue by JulijaRamoskiene** [dotnet/extensions#1754]
### To Reproduce
To reproduce:
1. Configure console logs with IncludeScopes set to true.
2. Add code to create some scopes and dispose them in unexpected order:
```csharp
public void Configure (IApplicationBuilder app, IHostingEnvironment env, ILogger<Startup> logger)
    {
    app.Run (async (context) =>
        {
        var testScope1 = logger.BeginScope ("Scope1");
        var testScope2 = logger.BeginScope ("Scope2");
        logger.LogError ("Created Scope1 and Scope2");
        using (logger.BeginScope ("InvisibleScope"))
            {
            testScope1.Dispose ();
            logger.LogError ("Disposed Scope1");
            testScope2.Dispose ();
            logger.LogError ("Disposed Scope2");
            }

        logger.LogError ("All scopes are now disposed.");
        await context.Response.WriteAsync ("Hello World!");
        });
    }
```
3. Run application and inspect logs.
With 2.2. version I got this:
```
fail: LoggingSampleApp.Startup[0]
      => ConnectionId:0HLN2L4355RRT => RequestId:0HLN2L4355RRT:00000002 RequestPath:/favicon.ico => Scope1 => Scope2
      Created Scope1 and Scope2
fail: LoggingSampleApp.Startup[0]
      => ConnectionId:0HLN2L4355RRT => RequestId:0HLN2L4355RRT:00000002 RequestPath:/favicon.ico
      Disposed Scope1
fail: LoggingSampleApp.Startup[0]
      => ConnectionId:0HLN2L4355RRT => RequestId:0HLN2L4355RRT:00000002 RequestPath:/favicon.ico => Scope1
      Disposed Scope2
fail: LoggingSampleApp.Startup[0]
      => ConnectionId:0HLN2L4355RRT => RequestId:0HLN2L4355RRT:00000002 RequestPath:/favicon.ico => Scope1 => Scope2
      All scopes are now disposed.
``` 
With 3.0 version i got this:
```
fail: LoggingSampleApp.Startup[0]
      => ConnectionId:0HLN2L07A1Q70 => RequestPath:/favicon.ico RequestId:0HLN2L07A1Q70:00000002, ActivityId:|e7ed6896-46bb14577968c4c4. => Scope1 => Scope2
      Created Scope1 and Scope2
fail: LoggingSampleApp.Startup[0]
      => ConnectionId:0HLN2L07A1Q70 => RequestPath:/favicon.ico RequestId:0HLN2L07A1Q70:00000002, ActivityId:|e7ed6896-46bb14577968c4c4.
      Disposed Scope1
fail: LoggingSampleApp.Startup[0]
      => ConnectionId:0HLN2L07A1Q70 => RequestPath:/favicon.ico RequestId:0HLN2L07A1Q70:00000002, ActivityId:|e7ed6896-46bb14577968c4c4. => Scope1
      Disposed Scope2
fail: LoggingSampleApp.Startup[0]
      => ConnectionId:0HLN2L07A1Q70 => RequestPath:/favicon.ico RequestId:0HLN2L07A1Q70:00000002, ActivityId:|e7ed6896-46bb14577968c4c4. => Scope1 => Scope2
      All scopes are now disposed.
```
### Expected behavior
- Scopes that are not disposed should be logged.
- Scope should not re-appear in logs after it was disposed
Expected log:
```
fail: LoggingSampleApp.Startup[0]
      => ConnectionId:0HLN2L4355RRT => RequestId:0HLN2L4355RRT:00000002 RequestPath:/favicon.ico => Scope1 => Scope2
      Created Scope1 and Scope2
fail: LoggingSampleApp.Startup[0]
      => ConnectionId:0HLN2L4355RRT => RequestId:0HLN2L4355RRT:00000002 RequestPath:/favicon.ico => Scope2 => InvisibleScope
      Disposed Scope1
fail: LoggingSampleApp.Startup[0]
      => ConnectionId:0HLN2L4355RRT => RequestId:0HLN2L4355RRT:00000002 RequestPath:/favicon.ico => InvisibleScope
      Disposed Scope2
fail: LoggingSampleApp.Startup[0]
      => ConnectionId:0HLN2L4355RRT => RequestId:0HLN2L4355RRT:00000002 RequestPath:/favicon.ico
	  All scopes are now disposed.
```

### Additional context
I would like to create scopes which would be disposed at a later stage, e.g. after request is completed:
```csharp
var scope = logger.BeginScope ("MyScope");
context.Response.RegisterForDispose (scope);
```

**Comment by anurse** [comment]
Scopes are not designed to be "jagged" like this. You are expected to dispose scopes in the same order than you create them. When disposed, the `IDisposable` representing the scope sets the current scope to whatever the parent scope was **at the time the scope was created**. So your Scope stack looks like this:

1. `BeginScope(Scope1)`: Root -> Scope1
1. `BeginScope(Scope2)`: Root -> Scope1 -> Scope2
1. `BeginScope(InvisibleScope)`: Root -> Scope1 -> Scope2 -> InvisibleScope
1. `Scope1.Dispose()` (Current scope is set to the parent of Scope1): Root
1. `Scope2.Dispose()` (Current scope is set to the parent of Scope2): Root -> Scope1
1. `InvisibleScope.Dispose()` (Current scope is set to the parent of InvisibleScope): Root -> Scope1 -> Scope2

It does seem like we could be better at throwing errors or otherwise handling scenarios where you dispose jagged scopes like this (since currently we restore old scopes because we just set the current scope to whatever the parent was at the time the scope is created) (cc @davidfowl). Still, we don't intend to change the behavior of scopes to allow jagged scopes like this. Your scopes should always be "spanning" (i.e each child scope is disposed prior to the parent scope being disposed).

**Comment by anurse** [comment]
Closing inactive discussion thread.

---

##### Note: Inactive closed issues are locked after 30 days since we don't triage closed issues and new comments tend to be lost. Feel free to post a new issue if this issue is locked and you have further questions/discussions. See [our issue management policies](https://github.com/dotnet/aspnetcore/blob/master/docs/IssueManagementPolicies.md) for more details.
