### ISSUE TITLE
Unable to build the source

### ISSUE THREAD

**Issue by hishamco** [dotnet/extensions#1931]
I just installed VS 2019, after that I run `build.cmd` but it takes awhile to download the SDK for ASP.NET Core 3.0.0 preview, so I decided to download it myself from dot.net, again when I run the previous command it keeps downloading the sdk

FYI I got those errors  in VS

Unable to find package Microsoft.DotNet.Arcade.Sdk. No packages exist with this id in source(s): nuget.org

C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\Sdks\Microsoft.DotNet.Arcade.Sdk\Sdk not found. Check that a recent enough .NET Core SDK is installed and/or increase the version specified in global.json.

/cc @pranavkm @ryanbrandenburg

**Comment by pranavkm** [comment]
cc @aspnet/build

**Comment by dougbu** [comment]
Builds work more reliably when the exact SDK required is installed in `{repo root}/.dotnet`. Using global installation can be a problem.

Suggest running `./restore.cmd` and waiting for it to complete before building.

**Comment by hishamco** [comment]
> Builds work more reliably when the exact SDK required is installed in {repo root}/.dotnet.

Is that mean I should paste the SDK version inside that folder? Coz the default path is C:\Program Files\dotnet

**Comment by hishamco** [comment]
Running `./restore.cmd` produce

dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-preview6-012264/dotnet-sdk-3.0.100-preview6-012264-win-x64.zip
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-preview6-012264/dotnet-sdk-3.0.100-preview6-012264-win-x64.zip
dotnet-install: Downloading legacy link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-preview6-012264/dotnet-dev-win-x64.3.0.100-preview6-012264.zip
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-preview6-012264/dotnet-dev-win-x64.3.0.100-preview6-012264.zip
at <ScriptBlock>, C:\Users\Hisham\Source\Repos\Extensions\.dotnet\dotnet-install.ps1: line 621
at InstallDotNet, C:\Users\Hisham\Source\Repos\Extensions\eng\common\tools.ps1: line 183
at InstallDotNetSdk, C:\Users\Hisham\Source\Repos\Extensions\eng\common\tools.ps1: line 169
at InitializeDotNetCli, C:\Users\Hisham\Source\Repos\Extensions\eng\common\tools.ps1: line 135
at InitializeBuildTool, C:\Users\Hisham\Source\Repos\Extensions\eng\common\tools.ps1: line 354
at InitializeToolset, C:\Users\Hisham\Source\Repos\Extensions\eng\common\tools.ps1: line 448
at Build, C:\Users\Hisham\Source\Repos\Extensions\eng\common\Build.ps1: line 78
at <ScriptBlock>, C:\Users\Hisham\Source\Repos\Extensions\eng\common\Build.ps1: line 133
at <ScriptBlock>, <No file>: line 1
(NETCORE_ENGINEERING_TELEMETRY=InitializeToolset) Could not find/download: ".NET Core SDK" with version = 3.0.100-preview6-012264
Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support

**Comment by dougbu** [comment]
Suggest you download the Zip file in a browser and expand it into `{repo root}/.dotnet`.

**Comment by hishamco** [comment]
After unzip and run restore I see the following error:

C:\Users\Hisham\Source\Repos\Extensions\artifacts\toolset\restore.proj : error : Unable to find package Microsoft.DotNet.Arcade.Sdk. No packages exist with this id in source(s): nuget.org
C:\Users\Hisham\Source\Repos\Extensions\artifacts\toolset\restore.proj : error MSB4236: The SDK 'Microsoft.DotNet.Arcade.Sdk' specified could not be found.
Build failed.

**Comment by hishamco** [comment]
@dougbu could you please help me on this, I'm stuck for weeks to run this on VS 2019 :(

**Comment by dougbu** [comment]
@hishamco I'm not sure what's going on except that geolocation of the CDNs, speed of your network, or the proxy settings is having a very negative impact on your `./restore.cmd` attempts. It's _possible_ to download the following and place it where `./restore.cmd` would but it isn't a one-step process as I'd hoped.

Since the largest downloads are the SDK and the runtime, suggest doing all of the following:
1. Download and expand [.NET Core SDK 3.0.100-preview6-012264](https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-preview6-012264/dotnet-sdk-3.0.100-preview6-012264-win-x64.zip) to `{repo root}/.dotnet`
2. Download and expand [.NET Core Runtime 3.0.0-preview8-27919-09](https://dotnetcli.azureedge.net/dotnet/Runtime/3.0.0-preview8-27919-09/dotnet-runtime-3.0.0-preview8-27919-09-win-x64.zip) to `{repo root}\.dotnet\shared\Microsoft.NETCore.App\3.0.0-preview8-27919-09`
3. Execute `./restore.cmd`
4. Execute `./startvs.cmd`

Another option would be to invoke `{repo root}/.dotnet/dotnet-install.ps1` directly with additional arguments e.g. `-AzureFeed {alternative to https://dotnetcli.azureedge.net/dotnet}`. It's a bit difficult to see how `dotnet-install.ps1` is normally invoked but you could edit the file to have it `Write-Host` the parameters it's given.

To determine an alternative URL, see whether the download web page is using something other than the script's default and copy that. If that's still https://dotnetcli.azureedge.net/dotnet, see if your browser is using a proxy (that Windows isn't aware of) and try passing `-ProxyAddress {address}`, perhaps with `-ProxyUseDefaultCredentials`.

Finally, `-noCdn` might work if https://dotnetcli.blob.core.windows.net (the default "uncached" URL) is more reachable than https://dotnetcli.azureedge.net (the default CDN).

**Comment by hishamco** [comment]
Again when I run `./restore.cmd` the previous error :(

**Comment by hishamco** [comment]
Running `dotnet-install.ps1` give me these errors:

./dotnet-install.ps1: line 6: syntax error near unexpected token `newline'
./dotnet-install.ps1: line 6: `<#'

**Comment by dougbu** [comment]
If you edited `dotnet-install.ps1`, you added a typo. Otherwise, the file was corrupted on download.

**Comment by hishamco** [comment]
I will try to download it again, but my question is from where can I get Arcade SDK?

**Comment by dougbu** [comment]
If you get enough files in their expected places, `./restore.cmd` will download the Arcade SDK and the Helix SDK.

**Comment by hishamco** [comment]
I download `dotnet-install.ps1` again and run it, download started with  https://dotnetcli.azureedge.net/dotnet/Sdk/2.1
.701/dotnet-sdk-2.1.701-win-x64.zip, it takes awhile, so I downloaded using download manger, put each folder on its place, bug I again when I run the previous command it starts to download the same file

**Comment by hishamco** [comment]
Any update on this, I'm still stuck with the tools :(

**Comment by Pilchie** [comment]
@dougbu @anurse ?

**Comment by dougbu** [comment]
@livar who owns the `dotnet-install.ps1` script and is it always downloading from US servers? Any suggestions to handle distant locations?

**Comment by hishamco** [comment]
Any updates, I'm still facing issues during build the source, I'm not sure if the problem that I'm in Middle East and the CDN is very slow

/cc @Eilon

**Comment by anurse** [comment]
Closing as this isn't something we control in our build scripts. We're just using the `dotnet-install.ps1` script provided on the dot.net website. I'd suggest filing a bug on [dotnet/core](https://github.com/dotnet/core) if that script is causing problems in certain areas due to it's use of a CDN.

**Comment by hishamco** [comment]
I think it's a CDN issue coz I try it in VM and it works great
