### ISSUE TITLE
Dependancy conflicts in Microsoft packages between redis and redis.strongname

### ISSUE THREAD

**Issue by Herostwist** [dotnet/extensions#2068]
I have an asp net core app with a few Microsoft packages. 

**Microsoft.AspNetCore.DataProtection.StackExchangeRedis** depends on **StackExchange.Redis**
**Microsoft.Extensions.Caching.Redis** depends on **StackExchange.Redis.StrongName**

Whenever I try and reference anything in the StackExchange.Redis namespace it causes a	CS0433 error.

Can you release a version of **Microsoft.Extensions.Caching.Redis** referencing **StackExchange.Redis** >= 2.0 so it plays nice with other Microsoft packages. Even a prerelease would be appreciated. 

Thanks.

**Comment by Tratcher** [comment]
https://github.com/aspnet/Announcements/issues/322
Microsoft.Extensions.Caching.Redis was replaced by Microsoft.Extensions.Caching.StackExchangeRedis

**Comment by Herostwist** [comment]
Super, that is good to know. A note to that affect would be very handy in the description on nuget - https://www.nuget.org/packages/Microsoft.Extensions.Caching.Redis

**Comment by anurse** [comment]
We'll use the deprecation feature in NuGet to do this when it's available: https://github.com/NuGet/Home/issues/2867

Updating the description on NuGet requires shipping an entirely new version which seems unhelpful as it will make users think a new version is available when it's just a description update.

**Comment by Herostwist** [comment]
Hmm, I see your dilemma. A depreciation feature is sorely needed on NuGet, especially considering if you search NuGet for "Microsoft Caching Redis" the depreciated Microsoft.Extensions.Caching.Redis comes up ahead of Microsoft.Extensions.Caching.StackExchangeRedis in the search results. I wonder how many people like myself have installed it with no idea that it has been replaced.

**Comment by inkel** [comment]
I've a similar problem. My project was already using `StackExchange.Redis.StrongName`, and when I added `Microsoft.Extensions.Caching.StackExchangeRedis` this is what I get when trying to `dotnet build`:

```
Redacted/Foo.cs(8,9): error CS0433: The type 'ConnectionMultiplexer' exists in both 'StackExchange.Redis.StrongName, Version=1.2.6.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46' and 'StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46' [/Users/inkel/foo/bar/Quux.csproj]
Redacted/Foo.cs(9,9): error CS0433: The type 'IDatabase' exists in both 'StackExchange.Redis.StrongName, Version=1.2.6.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46' and 'StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46' [/Users/inkel/foo/bar/Quux.csproj]
Redacted/Quux.cs(8,17): error CS0433: The type 'IDatabase' exists in both 'StackExchange.Redis.StrongName, Version=1.2.6.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46' and 'StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46' [/Users/inkel/foo/bar/Quux.csproj]
Redacted/Bar.cs(28,16): error CS0433: The type 'ConnectionMultiplexer' exists in both 'StackExchange.Redis.StrongName, Version=1.2.6.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46' and 'StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46' [/Users/inkel/foo/bar/Quux.csproj]
Redacted/Bar.cs(33,16): error CS0433: The type 'IDatabase' exists in both 'StackExchange.Redis.StrongName, Version=1.2.6.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46' and 'StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46' [/Users/inkel/foo/bar/Quux.csproj]
Redacted/Bar.cs(9,31): error CS0433: The type 'ConnectionMultiplexer' exists in both 'StackExchange.Redis.StrongName, Version=1.2.6.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46' and 'StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46' [/Users/inkel/foo/bar/Quux.csproj]
```

Any ideas how can I workaround this?

**Comment by anurse** [comment]
If you are able to update your usage to the newer `StackExchange.Redis` package which *is* strong-named, that is ideal. It will avoid the conflict.

If you can't update that, you should stick with [`Microsoft.Extensions.Caching.Redis`](https://www.nuget.org/packages/Microsoft.Extensions.Caching.Redis/)

**Comment by inkel** [comment]
I wasn't using `Microsoft.Extensions.Caching.Redis` to start with, and it was my understanding that, according to @Tratcher [comment](https://github.com/aspnet/Extensions/issues/2068#issuecomment-514055504), that the package was replaced by `Microsoft.Extensions.Caching.StackExchangeRedis`. I'd rather not stick with deprecated versions.

One possible [solution](https://stackoverflow.com/a/48758961) that I've found was to add the following to my `.csproj`:

```xml
  <Target Name="ChangeAliasesOfStrongNameAssemblies" BeforeTargets="FindReferenceAssembliesForReferences;ResolveReferences">
    <ItemGroup>
      <ReferencePath Condition="'%(FileName)' == 'StackExchange.Redis.StrongName'">
        <Aliases>signed</Aliases>
      </ReferencePath>
    </ItemGroup>
  </Target>
```

Although that seems quite hacky, it does the trick for now.

**Comment by anurse** [comment]
> I'd rather not stick with deprecated versions.

The same would generally apply to `StackExchange.Redis.StrongName` then. It's not *deprecated* per-se, but the 2.0 version is in a different package ([StackExchange.Redis](https://www.nuget.org/packages/StackExchange.Redis/), see [the StackExchange.Redis release notes for more](https://stackexchange.github.io/StackExchange.Redis/ReleaseNotes.html#20495)), so if you're going fix this conflict, I'd suggest doing it by updating `StackExchange.Redis`. The 2.x version of `StackExchange.Redis` **is strong-named**, so if you were avoiding that package primarily due to it not being strong-named, that has changed in StackExchange.Redis 2.x.

In general, the problem is crossing these two streams. In ASP.NET Core 2.1 and 2.2, the `Microsoft.Extensions.Caching.Redis` and `Microsoft.Extensions.Caching.StackExchangeRedis` packages are basically the same, they only differ on which Redis package they *depend upon*. ASP.NET Core 3.0 will only support `Microsoft.Extensions.Caching.StackExchangeRedis` so if you are planning to migrate soon, that's something to consider.

So it's a matter of choice, you have three options:

* Unify on `Microsoft.Extensions.Caching.Redis` and `StackExchange.Redis.StrongName`, though you will be limited to stay on ASP.NET Core 2.2 or earlier and StackExchange.Redis 1.x
* Unify on `Microsoft.Extensions.Caching.StackExchangeRedis` and `StackExchange.Redis`, which will keep you on the latest for both the caching component and the Redis client
* Use both via the Alias workaround you described above. As long as you don't need to transfer objects from one version to the other, this is fine. The framework will load both `StackExchange.Redis` and `StackExchange.Redis.StrongName` in memory and use them.

**Comment by inkel** [comment]
Thank you so much, @anurse ! This is a very detailed and useful answer. I think I'll go with the second option, I need to ask my team first, though. I'll let you know how it goes.

**Comment by KeithHenry** [comment]
It looks like `Microsoft.AspNetCore.All` points to `Microsoft.Extensions.Caching.Redis`, so you can't use it with `StackExchange.Redis`.

@anurse does that mean we need to expand out all the dependencies in `Microsoft.AspNetCore.All`?

Should the readme be updated to reflect that users shouldn't follow https://github.com/aspnet/Extensions#get-started as that adds `Microsoft.AspNetCore.All`?

**Comment by inkel** [comment]
Hi everyone, updates on this: we've replaced the dependency on `Microsoft.AspNetCore.All` with `Microsoft.AspNetCore.App`, and that worked fine for solving the issue mentioned with `StackExcange.Redis`.

I did have to update an unrelated dependency on `Microsoft.Extensions.Configuration.Binder` due to some down-versioning of said dependency. I've updated the dependency to `2.2.4` and now all warnings and errors disappeared.

Thanks for all the piointers!

**Comment by udlose** [comment]
> [aspnet/Announcements#322](https://github.com/aspnet/Announcements/issues/322)
> Microsoft.Extensions.Caching.Redis was replaced by Microsoft.Extensions.Caching.StackExchangeRedis

And of course having to do this is SO obvious.....maybe the .NET team should consider marking the methods in `Microsoft.Extensions.Caching.Redis` as `Obsolete`?  There should be an easier way to know this upgrade is recommended than having to Google for package conflicts and come across this as a result....
