### ISSUE TITLE
Trying to get Encrypted Xml to work

### ISSUE THREAD

**Issue by hodgsopg** [dotnet/extensions#2174]
### Describe the bug
I am trying to create and use an encrypted xml file with Microsoft.Extensions.Configuration.

The only example I can find is in the tests, but this example uses XmlConfigurationProvider Decryptor but this marked as internal in the code, so can't be used outside the namespace.

This part of the code is setting the key to be used to de-crypt the xml.
Is there another way to specify the key? I can't see any other way to do it.

### To Reproduce
1. Using version '3.0.0-preview7.19362.4' of package 'microsoft.extensions.configuration.xml'
2. Copy the code from function LoadKeyValuePairsFromValidEncryptedXml in this file: https://github.com/aspnet/Extensions/blob/master/src/Configuration/Config.Xml/test/XmlConfigurationTest.cs
3. Remove the Assert. lines and copy StringToStream from https://github.com/aspnet/Extensions/blob/master/src/Configuration/testassets/Test.Common/TestStreamHelpers.cs
4. We get 2 errors when compiling:
error CS1061: 'XmlConfigurationProvider' does not contain a definition for 'Decryptor' and no accessible extension method 'Decryptor' accepting a first argument of type 'XmlConfigurationProvider' could be found (are you missing a using directive or an assembly reference?)
error CS1729: 'XmlDocumentDecryptor' does not contain a constructor that takes 1 arguments
5. If you remove that code then when run it comes up with this exception
An unhandled exception of type 'System.Security.Cryptography.CryptographicException' occurred in System.Security.Cryptography.Xml.dll Unable to retrieve the decryption key.

### Expected behavior
I expected there to be a way to set the key I used to encrypt the xml file with.

### Additional context
I am using Visual studio version 16.3.0 Preview 1.0
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012821
 Commit:    6348f1068a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview7-012821\

Host (useful for support):
  Version: 3.0.0-preview7-27912-14
  Commit:  4da6ee6450

.NET Core SDKs installed:
  1.0.4 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.600 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012821 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by anurse** [comment]
The test is setting that property in order to mock out the default encrypted xml system since it's tied to OS behavior. In normal usage, the name of the key used to decrypt is embedded **within** the document itself (as a reference to an X.509 Certificate). The expected behavior here is that you have that certificate installed (with the private key available) in the Windows Certificate store.

The in-box XML configuration provider doesn't support using an arbitrary key to decrypt the data, it only supports using an X.509 certificate that is installed on the system.

**Comment by hodgsopg** [comment]
Can you point me to an example?
I was trying to work out how to use this code and this was the only code I found.

**Comment by anurse** [comment]
@hodgsopg Honestly, I probably can't. It's not a feature we've seen much use of and it was added a long time ago (back in v1) and basically hasn't been touched since. If you want to have encrypted configuration, it might be best to use the relatively new "stream" overloads for the various config providers and do the decryption yourself before loading config. For example: [`AddJsonStream`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.jsonconfigurationextensions.addjsonstream?view=dotnet-plat-ext-3.1) (and the other providers have similar ones).

With those, you can load your encrypted payload, wrap it up in a [`CryptoStream`](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.cryptostream?view=netcore-3.1) configured to decrypt it with the appropriate key and then pass it to `AddJsonStream` (or `AddXmlStream`, `AddIniStream`, etc.).
