### ISSUE TITLE
Is it correct that OptionsFactory is registered as a Transient?

### ISSUE THREAD

**Issue by Ermesx** [dotnet/extensions#2180]
Hello,

There is `OptionsManager<>` which has dependency on `IOptionsFactory<>`
``` c#
public OptionsManager(IOptionsFactory<TOptions> factory)
{
  this._factory = factory;
}
```

But registration of them looks like:
``` c#
public static IServiceCollection AddOptions(this IServiceCollection services)
{
    ...
    services.TryAdd(ServiceDescriptor.Singleton(typeof(IOptions<>), typeof(OptionsManager<>)));
    services.TryAdd(ServiceDescriptor.Scoped(typeof(IOptionsSnapshot<>), typeof(OptionsManager<>)));
    services.TryAdd(ServiceDescriptor.Transient(typeof(IOptionsFactory<>), typeof(OptionsFactory<>)));
    ...
}
```
So, it means singleton `OptionsManager` has dependency on transient `OptionsFactory` and it's look like captive dependency. There will be only one instance of OptionsFactory although is Transient.

I'm not sure if it's by disign or just a mistake.
Is there any explanation of that?

**Comment by HaoK** [comment]
This is correct, the factories are supposed to be transient, its up to the holder to determine the lifetime, singleton optionmanager will never need a new factory.  But a scoped snapshot would want a new factory every request.

**Comment by anurse** [comment]
Closing inactive discussion thread.

---

##### Note: Inactive closed issues are locked after 30 days since we don't triage closed issues and new comments tend to be lost. Feel free to post a new issue if this issue is locked and you have further questions/discussions. See [our issue management policies](https://github.com/dotnet/aspnetcore/blob/master/docs/IssueManagementPolicies.md) for more details.
