### ISSUE TITLE
Microsoft.Azure.Functions.Extensions AddScoped behaves like singleton

### ISSUE THREAD

**Issue by Planche95** [dotnet/extensions#2198]
Sample project: https://github.com/Planche95/AddScopedSample

```
public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            builder.Services.AddScoped(typeof(Foo));
            builder.Services.AddTransient(c => GetBar(c));
        }

        private Bar GetBar(IServiceProvider prov)
        {
            var foo = prov.GetService<Foo>();

            return new Bar(foo);
        }
    }
```
prov.GetService<Foo>(); always gets the same instance of Foo.

```
public class Bar
    {
        private readonly Foo _please;

        public Bar(Foo please)
        {
            _please = please;
        }
    }
```
Foo _please; is also always the same instance.

```
public class Function1
    {
        private readonly Foo _foo;
        private readonly Bar _bar;
        public Function1(Foo foo, Bar bar)
        {
            _foo = foo;
            _bar = bar;
        }

        [FunctionName("Function1")]
        public async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req)
        {
            return new OkObjectResult($"Hello");
        }
    }
```

looks like only inside Function Scoped working correctly. 

---

I'm using "Microsoft.Azure.Functions.Extensions" 1.0.0 which uses "Microsoft.Extensions.DependencyInjection" 2.2.0.

**Comment by anurse** [comment]
This is an issue that should be raised with the Azure Functions team. The only thing that `AddScoped` does is make it so that if you create a new scope with `IServiceScopeFactory`, then the `IServiceProvider` returned by that will have new instances. If they use the "root" scope when injecting into your function then it's by-design (in DI) that you'll always get the same instance.

ASP.NET Core creates a new scope for each request, which is why it "works" in ASP.NET Core. Functions would have to create a new scope per invocation.

I'd suggest filing a bug here: https://github.com/Azure/Azure-Functions.

Closing as this isn't something actionable from our side.
