### ISSUE TITLE
Duplicate keys in JSON configuration

### ISSUE THREAD

**Issue by aristotelos** [dotnet/extensions#2381]
When using `ConfigurationBuilder.AddJsonFile` to load settings from a `config.json` file, there is no exception when the content of the file contains a duplicate key.

### To Reproduce
1. Using version '2.2.0' of package 'Microsoft.Extensions.Configuration.Json'
2. Create a configuration file with contents:
```
{
    "my-duplicate-key": true,
    "my-duplicate-key": false
}
```
3. Run this code `ConfigurationBuilder.AddJsonFile`
4. An exception is expected, but the code continues without exception

### Expected behavior
An exception should be thrown that there is a duplicate key "my-duplicate-key" in the configuration file.

**Comment by gfoidl** [comment]
> Expected behavior

...or the behavior remains as is, but is documented -- right now there is no info in the docs what happens if duplicate keys are present.

**Comment by anurse** [comment]
I agree with @gfoidl here. I don't think we can justify the breaking change that would result from changing the behavior here. I do agree it should be documented though.

The current docs say this:

![A screenshot of the docs page linked below. See that link for details. The bullet point indicating "If a value for the same key is set by the same or different configuration providers, the last value set on the key is the value used.
" is highlighted.](https://user-images.githubusercontent.com/7574/73022453-7862db00-3dde-11ea-9b9f-c9afb01936fa.png)

From: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#keys

Perhaps that's not sufficient to help users find the expected behavior?

**Comment by aristotelos** [comment]
I really do not agree. Just accepting duplicate entries is a source of errors in real life. In my opinion, the world is better when this 'convention' is changed to throw an exception on load instead.

When this situation throws an exception immediately, a breaking change is not that bad because it is easy to detect. Please fix this before it is too late.

**Comment by Rick-Anderson** [comment]
Adding a note here for others that find this issue. See https://stackoverflow.com/questions/21832701/does-json-syntax-allow-duplicate-keys-in-an-object
