### ISSUE TITLE
Can asp.net core 3.0 support [Autowired] Attribute to implement Dependency injection

### ISSUE THREAD

**Issue by yunduansing** [dotnet/extensions#2406]
Can asp.net core 3.0 support [Autowired] Attribute to implements Dependency injection(just like Spring Boot @Autowired)？
eg:
`
[Autowired(LifeTime=Sington)]
private readonly IUserService userService{set;get;}`
Only construct inject is Not very friendly.

**Comment by davidfowl** [comment]
No, there's no plan to implement property injection.

**Comment by hey-hoho** [comment]
😂I need property injection too

**Comment by anurse** [comment]
Closing inactive discussion thread.

---

##### Note: Inactive closed issues are locked after 30 days since we don't triage closed issues and new comments tend to be lost. Feel free to post a new issue if this issue is locked and you have further questions/discussions. See [our issue management policies](https://github.com/dotnet/aspnetcore/blob/master/docs/IssueManagementPolicies.md) for more details.
