### ISSUE TITLE
Guidance on the usage of Compact() on a MemoryCache

### ISSUE THREAD

**Issue by Simon-Bull** [dotnet/extensions#2430]
### Problem description

I am using a MemoryCache to cache the result of a computationally expensive action on my ASP.NET Core 2.2 MVC application. The cached result can be used by subsequent requests. I am using the `AddMemoryCache()` extension and setting a size limit in the cache options of 2GB.
I'm then storing strings only in the cache and setting the cache entry sizes to be the length of the string.

When load testing to saturate the cache, what i'm observing is that the cache size limit will be reached, but soon afterwards memory continues to be consumed, putting the server under memory pressure and degrading performance.

![image](https://user-images.githubusercontent.com/8363325/65971210-bcad2280-e45f-11e9-9d23-488509abe0ec.png)

I understand that I ought to be calling [Compact](https://github.com/aspnet/Extensions/blob/v3.0.0-preview8.19405.4/src/Caching/Memory/src/MemoryCache.cs#L389) on the cache, to remove the least recently used entries and create space for new entries. I'm not currently doing this.

### Describe the solution you'd like
What I'd like to see is some guidance in the documentation on how and when it is appropriate to call `Compact()`. Some considerations I cannot find information on:

- When / how often should I check to see if `Compact()` ought to be called?
- Is calling `Compact()` computationally expensive? Is it proportionate to how much of the cache is compacted?
- Is doing this in a request-response context a bad idea? Will it block the request from completing until `Compact()` is finished?
- If calling in a request context is a bad idea, when should I call it? In a [BackgroundService](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.0&tabs=visual-studio#backgroundservice) perhaps?

Thanks in advance for any guidance on this matter.

ETA:
I set a long cache eviction time on my entries (24 hours). The keys are determined by a content hash and I am happy for LRU eviction to decide on entry removal.

**Comment by Tratcher** [comment]
> I'm then storing strings only in the cache and setting the cache entry sizes to be the length of the string.

FYI strings are two bytes per character. You're not limiting to 2gb, you're limiting to ~2,000,000 characters which is 4gb.

**Comment by Simon-Bull** [comment]
I've had a quite a voyage of discovery today about my understanding of MemoryCache. It went in this order:

- As you said @Tratcher strings consume more memory than their length. It's 2 bytes per character, plus a small amount of memory for object info.

- However, entries into a cache consume more memory than the object to be stored! The cache is fundamentally a collection of `ConcurrentDictionary<object, CacheEntry>`, seen [here](https://github.com/aspnet/Extensions/blob/master/src/Caching/Memory/src/MemoryCache.cs#L23)

- So, how do you determine how much memory a `CacheEntry` takes up? Well there's no nice (or not nice) way of reliably finding out an object's physical memory footprint (that I've found), and `CacheEntry` is not a trivial type, so actually trying to be accurate about the physical memory cost of an entry is now near enough impossible. 

I've decided to abandon this approach and use load tests to determine a conservative number of entries based on a representative sample of data that is being cached. E.g. each entry will count as 1 in a `SizeLimit` of 1000.

Setting a `CompactionPercentage` is trimming entries from the cache on an LRU basis, so this should suffice for my use case.

I do think that the documentation for this could be improved and made more explicit. Particularly given the [docs](https://github.com/aspnet/Extensions/blob/master/src/Caching/Memory/src/MemoryCache.cs#L23) state:
> If the web app was primarily caching strings, each cache entry size could be the string length.

Which i think is potentially quite misleading.

**Comment by Tratcher** [comment]
The main concept that's tricky to grasp here is that the cache size limit does not specify units, its intentionally not trying to measure memory because as you noticed, that's hard. The limit is in units of your own choosing, allowing you to assign weights to objects that make sense for your scenario. String length is a fine weight, it's directly proportional to the size of the object, but if your goal unit is in memory usage then you have to do some math.

**Comment by brandondahler** [comment]
Made a minor PR to docs to remove all instances of SizeLimit being referenced as the “memory size limit” - https://github.com/aspnet/AspNetCore.Docs/pull/15047

**Comment by brandondahler** [comment]
To answer more of your direct questions:

#### When / how often should I check to see if Compact() ought to be called?
Depends on multiple factors for your particular use-case.  You'll be trading off the benefit of releasing of stale entries versus the cost of checking each item to see if it is expired.  The cost of releasing items is linearly correlated to the number of items in the cache.

#### Is calling Compact() computationally expensive? Is it proportionate to how much of the cache is compacted?
Yes, to a degree.  It requires iterating every entry in the cache and checking if the entry is expired or not -- this process is O(n).  At the same time, it also builds 3 different lists for the different priorities in case it needs to remove more items in priority LRU mode to reach your target compaction amount -- the addition of these items into the lists are O(n log n) because we don't pre-allocate space into these lists.

Note that the Compact method will remove all expired entries regardless of the provided compaction percent or target removal size.

#### Is doing this in a request-response context a bad idea? Will it block the request from completing until Compact() is finished?
It is a bad idea, it will block the request from completing until Compact is finished.

#### If calling in a request context is a bad idea, when should I call it? In a BackgroundService perhaps?
I'd personally recommend calling it from a background thread, using any one of the many different ways that you can spawn background threads.  Internally, `ThreadPool.QueueUserWorkItem` is used for the `OvercapacityCompaction` feature for size limited caches.  

A BackgroundService that utilizes a Timer could be a perfectly valid way to call Compact on a interval-based basis.

#### Added - What literal method call/parameter value should I use?
This wasn't asked and I don't think is mentioned - there is no `Compact()` method, only `Compact(double percentage)`.  If you specify a non-zero percentage value, it will remove items in a priority LRU mode -- i.e. it will remove items that are potentially non-expired.  

If you want it to not remove items from the cache in LRU mode, you either need to:
* Add cache entries with `CacheItemPriority.NeverRemove`, or
* Call `Compact(0)` only

_____

In looking at these, I've found that some of the xml comments refer to "memory pressure" -- I plan to submit a PR to correct the wording appropriately.

**Comment by Tratcher** [comment]
Nicely said @brandondahler.

> In looking at these, I've found that some of the xml comments refer to "memory pressure" -- I plan to submit a PR to correct the wording appropriately.

Indeed, there used to be an application memory pressure mechanic but it was too unreliable so we removed it.

One other thing to consider is that it's common to use the cache without ever calling Compact. Cache entries have many built in triggers for their own removal depending on the expiration mechanism (e.g. IChangeToken, cancellation tokens, file change notifications, etc.). The cache also checks for expired items (by date/time) in the background every time you add something.

The real point of compact is to be called if you have some external indication that the application is low on memory or is entering an idle mode.

**Comment by Simon-Bull** [comment]
Thank you both @brandondahler and @Tratcher for the detailed responses. I think these two points in particular were relevant to my use case:

> There will be a significant amount of the items in the cache will likely expire during that period of time, and
> The amount of memory being tied up in the cache is important enough.

We were storing large (>100kb & <500kb) strings in MemoryCache and only relying on the LRU mechanism to invalidate and evict objects, which was happening at fairly high frequency because of a wide range of cacheable items, where the frequency of item access is highly variable.

When setting the size limit to 'sensible' value, we found that when under load, the Compaction would run each minute (or more often if configured), and those items evicted were no longer available in MemoryCache, but the memory being consumed was not being freed up.

We found that this was because the Garbage Collector was not being run while ASP.NET was under CPU load due to handling requests. Memory continued to be consumed until the server started to experience memory pressure.

This was occurring despite:
>The cache also checks for expired items (by date/time) in the background every time you add something.

I didn't test to see if calling `Compact()` would have helped this scenario.

A couple of potential mitigations to this scenario i don't like the idea of:
- We're hosting in IIS; so we 'could' limit the IIS app pool memory available.
- Manually invoke `GC.Collect()`

Neither of these feel like good ideas, especially `GC.Collect()`!

We've decided to not use MemoryCache for this case, as we have other processes running on the server (Node in our case) that contend for memory, and running production workloads where the server is under continuous memory pressure does not help with confidence from an operational point of view. We've concluded this application's requirements above are a poor fit for what MemoryCache is good at.

Thank you for looking to update the docs for MemoryCache, i think removing references to physical memory will help developers be more mindful of the right use cases for MemoryCache, and help disassociate the idea of physical memory being a direct and simple metric for `SizeLimit`

**Comment by Tratcher** [comment]
> We found that this was because the Garbage Collector was not being run while ASP.NET was under CPU load due to handling requests. Memory continued to be consumed until the server started to experience memory pressure.

Memory pressure is always the GC cleanup trigger. it doesn't matter if there is CPU load or not.

Removing the items from the cache does not remove them from memory, only the GC can do that. MemoryCache's job is to keep things from being GCd until you're done with them.
