### ISSUE TITLE
Could ConfigurationProviders load their data in parallel on start-up? 

### ISSUE THREAD

**Issue by ericstj** [dotnet/extensions#2569]
Copied from https://github.com/dotnet/corefx/issues/41743 @pekspro 

### Is your feature request related to a problem? Please describe.
I’m using both Azure KeyVault and Azure App Configuraton as ConfigurationProviders in a .NET Core 3 web application, also when I’m debugging. For me KeyVault adds about 5 seconds extra during launch, and App Configuration about 1 second. And this adds up to 6 seconds extra delay.

### Describe the solution you'd like
But couldn’t these providers load their data in parallel? It looks to me like they are running in serial, which make me loose one second every time I start to debug.

**Comment by anurse** [comment]
@pekspro The config system is currently synchronous so there isn't really a way to handle loading in parallel. Since the config system is layered, we have to apply each provider in the order given, so that later providers can override values in earlier ones. Certainly it could be refactored to allow providers to asynchronously load all their values in parallel and then merge them in sequence, but that would be a pretty significant change (and a very breaking one) so I don't expect the benefit would be worth that high cost to all existing customers.

**Comment by anurse** [comment]
Closing as we don't plan to change this. It would have a high risk of breaking customers and a high cost to refactor.
