### ISSUE TITLE
ConfigurationBinder should be able to convert an IPAddress

### ISSUE THREAD

**Issue by oswaldtech** [dotnet/extensions#2586]
Can the ConfigurationBinder be updated to convert and bind the IPAddress type?

Are there any technical reasons why this would not be a good idea?

**Comment by Tratcher** [comment]
IPAddress's have several formats. They're also commonly paired with ports which the original parser can't handle.
127.0.0.1
127.0.0.1:80
::1
[::1]
[::1]:80
[FE08::127.0.0.1]:80
etc.

Where do you intend to use the IPAddress?

**Comment by alex-oswald** [comment]
Our addresses use the first format in your list and don't include ports.

We have many manufacturing test applications (50+). These applications connect to multiple hardware devices via Ethernet (dmms, oscopes, rate tables, centrifuges, etc). We set static IP's for these devices and put the IP's in config for the application to load.

Using the first address format in your list, the binders `TryConvertValue` method returns `false` and the out parameter `result` is 'null` for `System.Net.IPAddress` because the `TypeDescriptor` cannot convert from a `string`.

**Comment by alex-oswald** [comment]
Apparently I am not the first. The current open issue for this is 497.
(aspnet/Extensions#497)[https://github.com/aspnet/Extensions/issues/497]

Though I still like the idea of this working without the `TypeConverterAttribute` on a bound property.
