### ISSUE TITLE
Expose some way to use DisposableObjectPool

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/extensions#2645]
### Is your feature request related to a problem? Please describe.
#973 introduced disposable object pool, but it is not exposed via public API. Manually casting the pool to `IDisposable` is considered implementation detail, and make it denied in certain projects.

### Describe the solution you'd like
Expose the pool type with `where T:IDisposable` constraint, and expose a factory for it.

### Additional context
The behavior of the pool should also be well documented.

**Comment by gfoidl** [comment]
>  and expose a factory for it.

There is `DefaultObjectPoolProvider`.
From https://github.com/aspnet/Extensions/pull/977

> `DefaultObjectPoolProvider` will choose on `T` which object pool to create. If `T` implements `IDisposable` the (new) `DisposableObjectPool` will be created, else the `DefaultObjectPool`.

Why do you think the `DisposableObjectPool<T>` should be public?

> The behavior of the pool should also be well documented.

For this see also https://github.com/aspnet/Extensions/issues/973#issuecomment-549964133

**Comment by huoyaoyuan** [comment]
> There is `DefaultObjectPoolProvider`.

The requirement is public signature of factory creation implements `IDisposable`.

> Why do you think the `DisposableObjectPool<T>` should be public?

The pool's lifetime is bounded to certain medium-life object. When the object is disposed, preserved objects in the pool should be also disposed.

**Comment by gfoidl** [comment]
When the `DisposableObjectPool<T>` gets disposed, all items held in the pool currently will get disposed.
Also you can use `ObjectPool.Create<T>` if you don't want to use `DefaultObjectPoolProvider`.

**Comment by huoyaoyuan** [comment]
> When the `DisposableObjectPool<T>` gets disposed

If `DisposableObjectPool` is not exposed, this will require *casting `ObjectPool<T>` to `IDisposable`*, which was strongly rejected.

**Comment by mvarblow** [comment]
If you're using DI to construct your object pool then the DI service collection will see that the object pool implements IDisposable and will invoke the Dispose method for you. No need for you to cast and dispose it.

See https://docs.microsoft.com/en-us/aspnet/core/performance/objectpool#objectpool-sample for an example of using DI to construct your object pool. In this example, the pool will be disposed on shutdown since it is created as a singleton. If the pool was created as a transient or scoped service then the lifetime would obviously be shorter and Dispose called earlier.

**Comment by huoyaoyuan** [comment]
> If you're using DI to construct your object pool

Obviously, I'm not using DI, and the project structure is fundamentally unsuitable for DI.

**Comment by mvarblow** [comment]
Not sure how that was obvious. :)

It also seems unnecessary to me that DisposableObjectPool be kept internal. The only reason I can see for doing that is to avoid confusion. These classes are very lightly documented so keeping DisposableObjectPool internal and out of the documentation helps avoid confusion for people who should not be using it directly -- most people using this library **are** using DI. But a bit of doco on the classes themselves could solve that problem.

**Comment by anurse** [comment]
So the ask here is for us to take the internal implementation detail (`DisposableObjectPool`) and make it public?

> It also seems unnecessary to me that DisposableObjectPool be kept internal. The only reason I can see for doing that is to avoid confusion.

That's not how we assess public APIs. In order for an API to be public it must have a strong benefit to being public **and** be something the team can maintain as a public API. Public APIs are **very** costly as they require constant maintenance and support and adding a new one here *will* take resources away from other higher-priority work. Plus, if we made it public it would be in the DI assembly, so it would be weird for non-DI people to use (and making a new assembly is *even more costly*).

To me this sounds like a place where the OSS model is perfect. The type is `internal` but the logic is public, right here on GitHub. Someone who does want to take on the maintenance burden could take it, wrap it up in a package and publish it.

**Comment by huoyaoyuan** [comment]
> Plus, if we made it public it would be in the DI assembly

I don't understand this. Object pools have concrete usage scenarios, and have their own assembly. Disposal is also a widely used concept. It looks incorrect to treat it as a subcomponent of DI.



> Someone who does want to take on the maintenance burden could take it, wrap it up in a package and publish it.

The issue was opened to get rid of copying code ourselves. Unfortunately, it seems that we have to do this.

**Comment by anurse** [comment]
> I don't understand this. Object pools have concrete usage scenarios, and have their own assembly. Disposal is also a widely used concept. It looks incorrect to treat it as a subcomponent of DI.

Exactly, it **is** incorrect to treat it as a subcomponent of DI. The point is that in order to make a proper public API here, we have to build, maintain and support a brand new package and brand new assembly. This is not trivial cost. I didn't want to put this on the backlog when the reality is I don't expect we'll ever be able to prioritize the work needed enough to bring it up. Right now, this type is an implementation detail of DI and we have no commitment or intent to support it more than that. There are a lot of little types like this spread across Extensions (and I'm sure all your projects), but we can't reasonably maintain all of them as public APIs.
