### ISSUE TITLE
Is NuGet major version upgrade allowed or not? Microsoft.Extensions.Logging.Abstractions

### ISSUE THREAD

**Issue by rlaci999** [dotnet/extensions#2700]
### Describe the bug
We have `netstandard2.0` projects with `EF Core` `2.2.6`. I tried to upgrade a console application's NuGet `Microsoft.Extensions.Logging.Abstractions` from `2.2` to `3.0.1` but got runtime error:

> Could not load type 'Microsoft.Extensions.Logging.Abstractions.Internal.NullScope' from 
> assembly 'Microsoft.Extensions.Logging.Abstractions, Version=3.0.1.0 

The error message seems legit, because `NullScope` was removed: [[Compare link]](https://www.fuget.org/packages/Microsoft.Extensions.Logging.Abstractions/3.0.1/lib/netstandard2.0/diff/2.2.0/?code=true), and Semantic Versioning enables breaking changes at major version change.

**But why is it not written at the NuGet dependencies?** [[NuGet link]](https://www.nuget.org/packages/Microsoft.Extensions.Logging.Abstractions/3.0.1)

There are some other `Microsoft.Extensions.*` `3.0.1` packages that seem working well.

**What is the right way to determine on which version can I update? Is it mandatory to stick to always the current major version?**
If so, then at which NuGets? For example `Microsoft.NET.Test.Sdk` `16.4.0` works pretty well.

### To Reproduce
See above. I can provide further details if needed.

### Expected behavior
Maybe change dependencies of ...Abstractions package to (>= .NETStandard 2.1)
Or advise how to handle these version decisions.

**Comment by Bert-Proesmans** [comment]
I'm having a similar issue. Required libraries cannot be loaded due to unpinned library versions.

A lot (if not all) of libraries reference their *.Abstractions library without version.
In my case i have an sdk-style c# library that is used by my csproj-style with packagereference test project.
In both projects EFCore, pinned to 2.2.6, is used and MS.EntityFrameworkCore a direct dependency. At runtime the test project crashes on not being able to load the MS.EXT.Logging.Abstractions, or MS.EXT.DI.Abstractions in the 2.X range. Seems like a pinned dependency on MS.EXT.Logging and MS.EXT.DI itself is not enough to guarantee working software, since NuGet automatically resolves the latest *.Abstractions (3.X currently).

I cannot automatically generate assembly redirects for my test project: nothing happens. I'm also unaware of this being documented anywhere.
If possible i'd like some guidance on how to solve this issue. The naïve approach would be to manually make all required *.Abstractions packages direct dependencies on all my projects, but that will require a lot of manhours to fix. (Moving to sdk style projects and package references was already a lot of work because i didn't know of any way to automate this)
These kind of issues drive me to the point of being unhappy when working with C#.

**Comment by rlaci999** [comment]
You should follow Semantic Versioning approach. If your project is `<TargetFramework>netcoreapp2.1</TargetFramework>`
you should choose **Microsoft.Extensions.*** versions to that start with 2.1, like:
```
<PackageReference Include="Microsoft.Extensions.Configuration" Version="2.1.1" />
<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="2.1.10" />
```
but **NOT** 2.2.* or 3.*

**Comment by Bert-Proesmans** [comment]
Thank you for the suggestion.

I think I have figured out how I should go about my dependencies now. 
As I understand how I ended up in my situation: NuGet prefers to resolve from the package cache of the current solution. Projects that are not in my dependency chain with higher versions still affected the resolved version of other projects. Either I missed some unnecessary reference with too new dependencies, or I couldn't find out how to instruct NuGet to recalculate the dependency graph with lower dependencies (if possible).
In the end, I downgraded every first and second order dependencies within my solution to consolidate on handpicked versions. Now I also see the benefit/reason why IntelliSense suggests locally cached packages to depend on first, instead of going through the NuGet package manager UI.

In the end, semantic versioning is just a guiding principle for consumers. Library maintainers are the targetted users that should lay out constraints according to the spec. Of course, this applies to me as well when I transitively build libraries for others to consume.

**Comment by anurse** [comment]
To answer the original question: You should try to ensure your `Microsoft.Extensions.*` packages have the same major version across all your dependencies. While it is *possible* to cross major version boundaries, we do make breaking changes between major versions which can cause runtime failures. If you happen to avoid all those breaking changes, it will likely work, but we don't recommend it.

**Comment by Bert-Proesmans** [comment]
I understand the sentiment, but the fact that the Nuget dependencies are not limited to a maximum version is basically a trap.

It's very realistic to indirectly depend on `Microsoft.Extensions.*` packages through some 3rd party dependency. A lot of dependencies don't share the MS agenda of supporting specific NET platforms for specific versions of their packages.
NuGet happily includes 2.x package references with 3.x second-order references already cached. As a programmer, you fall into this trap. This can be and should be avoided.
Not properly defining bounds on your NuGet referenced package versions is a bad signal to developers, IMO.

My reality is that I try to stay away from all `Microsoft.Extensions.*` packages where possible. They are all interwoven and only 'just work' when you keep up to date with the latest releases.
