### ISSUE TITLE
Can't Register Instance of IStartup in Generic Host

### ISSUE THREAD

**Issue by thefringeninja** [dotnet/extensions#2732]
According to aspnet/Hosting#333 the following used to be sufficient to use an _instance_ of an `IStartup` when starting kestrel:

```
internal static class WebHostBuilderExtensions {
  public static IWebHostBuilder UseStartup(this IWebHostBuilder builder, IStartup startup) =>
    builder.ConfigureServices(services => services.AddSingleton(startup));
}
_host = new WebHostBuilder()
  .UseKestrel()
  .UseStartup(new MyStartup(someDep))
  .Build();
```

However, using the new generic hosting bits, this no longer works. 

```
_host = Host.CreateDefaultBuilder()
  .ConfigureWebHost(builder => builder
    .UseKestrel()
    .UseStartup(new MyStartup(someDep)))
  .Build();

crit: Microsoft.AspNetCore.Hosting.Diagnostics[6]
      Application startup exception
System.InvalidOperationException: No application configured. Please specify an application via IWebHostBuilder.UseStartup, IWebHostBuilder.Configure, or specifying the startup assembly via StartupAssemblyKey in the web host configuration.

```

**Comment by anurse** [comment]
To be clear, is `UseStartup` implemented the same way in the generic host model (by registering it in DI)? That doesn't work in generic host, we no longer use DI to resolve the startup class (the container doesn't exist yet).

**Comment by anurse** [comment]
https://github.com/aspnet/AspNetCore/issues/11050 is tracking work on finding alternatives to `IStartup` in generic host.

**Comment by anurse** [comment]
Closing inactive discussion thread.

---

##### Note: Inactive closed issues are locked after 30 days since we don't triage closed issues and new comments tend to be lost. Feel free to post a new issue if this issue is locked and you have further questions/discussions. See [our issue management policies](https://github.com/dotnet/aspnetcore/blob/master/docs/IssueManagementPolicies.md) for more details.
