### ISSUE TITLE
Share user secrets in Dev-Teams

### ISSUE THREAD

**Issue by mgeramb** [dotnet/extensions#2739]
The current mechanism for user screts in development environment (https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-3.0&tabs=windows) stores the secrets in a json file which is stored on the local machine for the current user.
But for development teams, it would be nice to share the secrets, so that not every team member must configure the same passwords.

The current tool `dotnet user-secrets` and the extension for user secrets  stores the secrets in a folder depending on the following environment variables (https://github.com/aspnet/Extensions/blob/master/src/Configuration/Config.UserSecrets/src/PathHelper.cs):

- APPDATA (Windows)
- HOME (Linux)
- Environment.SpecialFolder.ApplicationData
- Environment.SpecialFolder.UserProfile
- DOTNET_USER_SECRETS_FALLBACK_DIR

**Simple Solution**

A simple solution to share secrets in a Team would be to let configure a network folder as storage location for the secret files.

e.g. The PathHelper could make an additional lookup as first step with the environment variable
`DOTNET_USER_SECRETS_DIR`

So each team member can set this variable one time to a shared folder to share the secrets (https://github.com/aspnet/Extensions/pull/2726).

**Flexible Solution**

Another possiblity would be, to store a 'directory-json' file in the root folder of the secrets which contains the location for project secrets files on project Level.
e.g. the user excute:

    dotnet user-secrets setlocation "\\SERVER\Projects\MyProject\UserSecrets" --project "C:\apps\WebApp1\src\WebApp1"

This would create a directory json in the default root directory of user secrets storage location:

```JSON
[
   {   "userSecretsId": "79a3edd0-2092-40a2-a04d-dcb46d5ca9ed",   "location:": "\\\\SERVER\\Projects\\MyProject\\UserSecrets" }
]
```

All future request to the secret json files will be redirected to the project specifc location.

**Comment by anurse** [comment]
cc @Tratcher @davidfowl 

> But for development teams, it would be nice to share the secrets, so that not every team member must configure the same passwords.

My initial concern here is that user secrets was very intentionally designed around **not** sharing secrets. It's the whole reason it exists. Generally we've suggested using other systems to share secrets, even for development scenarios (things like Azure Key Vault, or custom config providers).

Just expanding this to allow a custom directory isn't a huge deal, but it does expand our security model for this.

Using an environment variable is very risky, since updating this env var could end up messing with other projects. A "redirector" file in the default location could work but feels overly complicated.

Just adding the ability for the `dotnet user-secrets` command to target another file doesn't seem too scary. It could be a command-line argument and you could easily have some scripts that set up the correct arguments and proxy the rest of the arguments through (`.\my-project-secrets set 'Foo' 'Bar'` which just calls `dotnet user-secrets --location \\SERVER\... set 'Foo' 'Bar'`)

When adding something like this to the *product* a big question we need to consider is "Does this add value to a large group of users?". I'm not so sure that value is clear right now. The user-secrets tool has a relatively significant maintenance burden today (flaky infrastructure, VS tooling integration code, etc.). This is the first report I've heard of asking for this (though I may be missing something). It seems to me like this is a better place for a third-party tool and provider (based on the existing code) to explore, and we could investigate a first-class option when there is more data to show the value to existing customers.

**Comment by anurse** [comment]
Another option: Have you tried creating a symbolic link to place the shared file in the normal location? https://winaero.com/blog/create-symbolic-link-windows-10-powershell/

If there are bugs in the handling of symlinks, we could look at fixing those.

**Comment by mgeramb** [comment]
Yes, the symbolic link could work for the team problem. But a build in feature would support more scenarios. E.g. The user secrets can currently only used in Dev-Environments, with a build in feature where the location can be specified, it could also be used in PROD-Environments to separate the secrets from the appsettings. For this case, the simple solution with the environment variable would be enough, the variable could be specified in the web.config, so it must not be machine wide.

> Using an environment variable is very risky, since updating this env var could end up messing with other projects. A "redirector" file in the default location could work but feels overly complicated

This is true, but the indention was to use this on dev-machines with a single owner. There exist currently already the same "risky" solution with the [.net core environment](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-3.1) where a variable can be used to the define the environment name which will be used for the selection of the corresponding application settings files. This also could break other applications on the same machine, so the developer have to know what he do. My solution with the environment variable for the store location is very similar, so it used the same concept, is fully downward compatible, easy to implement and offers a lot of new scenarios:

- Dev-Team secret sharing
- Usage on PROD machines to separate appsettings and secrets in the same way
- Easy usable in docker environments to place the secrets on a mount point

 > This is the first report I've heard of asking for this
One is always the first. But the discussion is open now. Maybe other people find this usefully but have not yet thought about this.

**Comment by anurse** [comment]
> One is always the first. But the discussion is open now. Maybe other people find this usefully but have not yet thought about this.

Yep, we just don't have enough data to consider this worth the high cost of integrating it into the main product at this.

**Comment by anurse** [comment]
Closing as we don't believe this is something the core user secrets component should provide. We can always review this as we hear more from users.
