### ISSUE TITLE
Testing/confirming dependency injection

### ISSUE THREAD

**Issue by thomasheartman** [dotnet/extensions#2857]
### Is your feature request related to a problem? Please describe.
One consistent problem my team and I keep running into is with dependency injection. More specifically: forgetting to register a service---or more recently: injecting a class that has more rigid constraints than the interface (through open generics)---causing runtime exceptions.

### Describe the solution you'd like
If there already is a solution for this, please feel free to point me to it. I have tried searching around, but haven't found any solutions to this. However, I am quite open to the idea that I may just not have looked closely enough.

The ideal solution to this would be compile-time checks to avoid the runtime exceptions, but this seems unlikely. Another way would be to have some standardized tests that run across all classes and check that they can resolve all the dependencies and that the public API works as expected. 

Thanks!

**Comment by t-hart** [comment]
Hey,

I see that the issue's been moved around a bit and had a few labels assigned. That's great, because it probably means that someone is aware of it. However, I was wondering if I could get a written response to the issue, just to make sure that it isn't forgotten and to clarify what exactly the current state of things is. 

With no one having said anything (and based on the 'enhancement'-label), I'm assuming this isn't a feature that is available right now. Is that correct?

Sorry to cause you any extra work.

**Comment by anurse** [comment]
Sounds like this is resolved to your satisfaction then @thomasheartman ? We do indeed have a validation mode in DI that will try to eagerly check your services to make sure there are no cycles, etc. It's not enabled by default because it can dramatically impact startup performance.

Feel free to comment further or open new issues if you have further questions! Apologies for the delay in responding!

**Comment by thomasheartman** [comment]
Thanks, @anurse . Yes, it did indeed solve my problem. It definitely impacts startup perf, but we'd rather have something break immediately than at some unspecified point in the future.

The one thing I'd like to leave as a comment is a wish that this was easier to find. As mentioned previously, I did spend a lot of time and effort searching for the answer, so avoiding that in the future would be great. That said, I don't know where exactly it should be documented or how, so maybe it's not much better at all.

**Comment by anurse** [comment]
It is mentioned in the docs on [Dependency Injection](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1#scope-validation), but not in much detail. If you’ve got suggestions for the docs, feel free to leave that on the docs pages and our docs team can take a look! You can also send a PR to update them if you have specific thoughts on what might make it clearer!
