### ISSUE TITLE
RedisTimeoutException missing IOCP and WORKER in log

### ISSUE THREAD

**Issue by bmasnec** [dotnet/extensions#2870]
### Describe the bug
Hi,
I'm using .Net Core app 2.2 with explicit reference to Netstandard 2.0.3 library.

For some reason there is no IOCP and WORKER stats in log when timeout occur. 
From documentation the log part should be present 
> IOCP and WORKER threads will not be shown on .NET Core if using netstandard < 2.0

I'm using Netstandard 2.0.3 which is latest available. Microsoft.Extensions.Caching.Redis SDK version in use is 2.2.0 
And here is log that i get

ExceptionStackExchange.Redis.RedisTimeoutException: Timeout performing EVAL, inst: 14, queue: 42, qu: 0, qs: 42, qc: 0, wr: 0, wq: 0, in: 11373, ar: 0, clientName: ActivityService, serverEndpoint: Unspecified/cache.amazonaws.com:6379, keyHashSlot: 15753 (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)

### Expected behavior
IOCP and WORKER threads should be in log

Can you advise me or point me in right direction

**Comment by anurse** [comment]
This sounds like a question for the StackExchange.Redis team. I don't believe we configure anything that would prevent this logging. Can you file an issue over on their repo: https://github.com/StackExchange/StackExchange.Redis ? If it turns out to be a configuration issue on our end, we can revisit.
