### ISSUE TITLE
HttpClientFactory deadlocks in single-threaded SynchronizationContext for 2.1.*

### ISSUE THREAD

**Issue by Kahbazi** [dotnet/extensions#3023]
Is Microsoft.Extensions.* version 2.1.* in LTS support? If so is it possible to fix https://github.com/dotnet/extensions/issues/999 in 2.1 package?

**Comment by Kahbazi** [comment]
@anurse Is there any chance this get fixed is 2.1 ?

**Comment by anurse** [comment]
I'm not sure. @rynowak ?

**Comment by rynowak** [comment]
Why is it up to me? I don't decide when or what we patch 😆

**Comment by Kahbazi** [comment]
@anure Who can decide on this patch? I used a workaround for the deadlock and it's in production but I would like to update the package if it's going to be patched. 🙂

**Comment by anurse** [comment]
> I used a workaround for the deadlock

The fact that there's a workaround generally excludes it from backporting. Keeping code changes to the absolute minimum is very important in LTS in order to ensure users feel safe upgrading, so anything with a workaround generally doesn't get backported.

Also, we have a doc on our [Servicing Process](https://github.com/dotnet/aspnetcore/blob/master/docs/Servicing.md) that includes information about how we evaluate backporting now!
