### ISSUE TITLE
Using IOptionsSnapshot in httpclient registration

### ISSUE THREAD

**Issue by cannehag** [dotnet/extensions#3062]
### Question
We are switching over to using Azure AppConfiguration and are moving to having our services automatically reload configuration in real time. I'm trying out a thing here by wanting to change the BaseAddress of a HttpClient registered with AddHttpClient().
The problem seems to be that it's not possible to use IOptionsSnapshot<T> this way:
```
services.AddHttpClient<IClient, Client>((serviceProvider, client)=>{
  var settings = serviceProvider.GetRequiredService<IOptionsSnapshot<AppSettings>>();
client.BaseAddress = settings.Url;
});
```

```Cannot resolve scoped service 'Microsoft.Extensions.Options.IOptionsSnapshot`1[AppSettings]' from root provider.```

I may be on the wrong path here since I don't know if it's even possible to make changes to the HttpClient factory registration after startup has executed. Is that possible?

**Comment by rynowak** [comment]
I think what's going to matter in this case is actually what service provider you're using to retrieve the `HttpClient`. The callback that you provider here should be running every time you resolve `HttpClient` from DI.

Can you show me more? Where is this resolved from?

**Comment by cannehag** [comment]
@rynowak 
That's probably true yes.
But I actually got it working by registering the IOptionsSnapshot<T> using a transient factory instead of singleton. The problem is that the serviceprovider used in AddHttpClient seems to be the root provider. And since IOptions registration (using services.Configure()) add's IOptionsSnapshot<T> as singleton, it's not allowed to be resolved.

**Comment by rynowak** [comment]
Did you try using `IOptionsMonitor<>`? That's a singleton and it allows access to the current value (like snapshot does). You should be able to do this without hacking anything.

The reason why snapshot is scoped is so that all of the collaborators within a scope can all see the **same** values for the options. Things would be broken if there were possible race conditions within an ASP.NET Core requests (for example) because 3 different components all got different values of `IOptionsSnapshot<>`.

**Comment by cannehag** [comment]
Actually, the IOptionsMonitor<T> is what I use now! :)
So, let's close this issue. Thanks!

**Comment by rynowak** [comment]
Ok great. That's a better solution than changing the lifetime of snapshot 👍
