### ISSUE TITLE
Environment Variable interpolation in config files

### ISSUE THREAD

**Issue by erwan-joly** [dotnet/extensions#3101]
### Is your feature request related to a problem? Please describe.
It would be nice to have a way to inject environment variables into configuration based on a configuration file. I think environment variables are out of specs in json / yml but a lot of software actually support such a feature.

### Describe the solution you'd like
It would just require to interpolate ${ENVIRONMENT_VARIABLE} when found during the build phase.

### Describe alternatives you've considered
My current idea of alternative is to use configuration stream instead of file and parse the stream to replace all ${ENVIRONMENT_VARIABLE} by their current value.

### Additional context
Such a feature seems to be quite usual (mainly with yml configuration) in a lot of system. A good example: docker-compose.

**Comment by anurse** [comment]
I don't think it's correct layering to put this in the config system. Especially since it would be limited to a fixed source like Environment Variables. Putting it on top would mean interpolated values could come from other sources (including other configuration keys). This seems like an interesting idea for a third-party component but not something we'd built in to the core config system.
