### ISSUE TITLE
Update TryAddSingleton to support fluent configuration

### ISSUE THREAD

**Issue by lg2de** [dotnet/extensions#3112]
### Wished configuration
```cs
serviceCollection
    .TryAddSingleton<IInterface1, Implementation1>()
    .TryAddSingleton<IInterface2, Implementation2>();
```

### Describe the solution you'd like
Return `IServiceCollection` from `TryAddSingleton`.

I would like to use fluent configuration, similar to `AddSingleton<>`.

### Describe alternatives you've considered
```cs
serviceCollection.TryAddSingleton<IInterface1, Implementation1>();
serviceCollection.TryAddSingleton<IInterface2, Implementation2>();
```

**Comment by anurse** [comment]
There was another issue suggesting it return `bool` indicating if it was successful, which would obviously conflict with this. Neither option really seems worth the fairly significant breaking change this would introduce (since return values are part of the method signature and written in to the calling IL).
