### ISSUE TITLE
Version mismatch between corresponding libraries

### ISSUE THREAD

**Issue by KarelM2** [dotnet/extensions#3374]
I get assembly load errors after upgrading multiple Microsoft.Extensions.Configuration.* from 3.1.0.0 to 3.1.6.0. All updated libraries to 3.1.6.0 still seem to depend on 3.1.0.0 versions of the related / dependent libraries.

LOG: DisplayName = Microsoft.Extensions.Configuration.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
 (Fully-specified)
LOG: Appbase = file:///C:/workspace/repos/petrel/wwwroot/
LOG: Initial PrivatePath = C:\workspace\repos\petrel\wwwroot\bin
Calling assembly : Microsoft.Extensions.Configuration, Version=3.1.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60.

**Comment by Pilchie** [comment]
See #2931.  This is basically by design to support being able to pick up fixes in the ASP.NET Core shared framework.

**Comment by lukos** [comment]
I know the original has been closed "by design" but this would count as a critical bug in most organisations, regardless of the fact it wasn't intended and there are generally "workarounds". Even though our domain is only about 30 applications using netstandard shared libraries, we probably spend an hour every time we make a significant update trying to track and fix broken redirects. 

Sometimes we get compiler errors, sometimes not, sometimes apps fail but other times it is just the integration tests or something else late at night when we are trying to deploy something, some apps we change frequently and are likely to spot sooner, others we don't.

Just the other day, I spent pretty much all of it just trying to update and fix nuget versions and even with everything up-to-date, the bug still persists because of the mismatched versions. The workarounds are not quick and easy so you guys really need to crack on with a solution because a lot of us are really fed up with wasting our time doing things that nuget/vs/msbuild are supposed to do automatically.

Just the sheer number of reported problems must show you that this is not an acceptable breaking change? Many of us have legacy apps and will do for a long time. Is anything in progress to fix this?

**Comment by chucklu** [comment]
I am using  the following two packages which depend on  Microsoft.Extensions.Configuration (>= 3.1.6), and Microsoft.Extensions.Configuration depends on Microsoft.Extensions.Configuration.Abstractions (>= 3.1.6).
```xml
<PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="3.1.6" />
<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="3.1.6" />
```
https://www.nuget.org/packages/Microsoft.Extensions.Configuration.Json/3.1.6
https://www.nuget.org/packages/Microsoft.Extensions.Configuration/3.1.6
![image](https://user-images.githubusercontent.com/3004057/88886151-6f126980-d26c-11ea-9beb-60f8d34c04dc.png)


However when I try to check the inner binding of Microsoft.Extensions.Configuration by [dnSpy](https://github.com/0xd4d/dnSpy), the file info of Microsoft.Extensions.Configuration.dll is
Microsoft.Extensions.Configuration, Version=3.1.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
The fie hash is SHA-256: 9f4020eeb17b6506a69253d26646a4217911a1ae89c2598f492d1c45a0212503
```powershell
 [System.Diagnostics.FileVersionInfo]::GetVersionInfo("Microsoft.Extensions.Configuration.dll").ProductVersion
```
3.1.6+be18161fbed286d6fb7a7b1c7999ce70a50cf3eb

And the reference of Microsoft.Extensions.Configuration is 
// Microsoft.Extensions.Configuration.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
// Microsoft.Extensions.Primitives, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
// netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
Why the 3.1.6 version of Microsoft.Extensions.Configuration depend on `Microsoft.Extensions.Configuration.Abstractions, Version=3.1.0.0`, and the nuget document told me it depends on  `Microsoft.Extensions.Configuration.Abstractions (>= 3.1.6)`


You might make same mistake as me here https://github.com/dotnet/sdk/issues/9594#issuecomment-666131197.
Is it possible for you to dotnet pack the Microsoft.Extensions.Configuration 3.1.6  along with  Microsoft.Extensions.Configuration.Abstractions 3.1.6 .

**Comment by chucklu** [comment]
@Pilchie  ` This is basically by design to support being able to pick up fixes in the ASP.NET Core shared framework.`
Could give us more detail about what you are talking about? 
What's the official definition for `ASP.NET Core shared framework`? What's the usage of it? and when you talk about` being able to pick up`, who or what did pick up？
I tried to Google this concept `ASP.NET Core shared framework`, there is no documentation about it, and only got a closed question here https://stackoverflow.com/questions/57650522/what-is-net-core-shared-framework

**Comment by chucklu** [comment]
Find the document https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage-app?view=aspnetcore-3.1
https://natemcmaster.com/blog/2018/08/29/netcore-primitives-2/
It's weird the title is "Microsoft.AspNetCore.App for ASP.NET Core", maybe you can change the title to The ASP.NET Core shared framework

**Comment by chucklu** [comment]
Just notice the nuget did the [bindingRedirect ](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/bindingredirect-element)automatically under App/Views/web.config of my mvc project.
I did not realized it before because my local mvc project did not include App/web.config in to .csproj file. It seems the nuget just write the bindingRedirect to the first web.config it can found in .csproj file.

**Comment by chucklu** [comment]
@KarelM2  What kind of project do you use? The nuget was expected to do the bindingRedirect for you automatically.

**Comment by KarelM2** [comment]
The project is subject to a big enterprise application with a diverse amount of third party dependencies. 
The code base suffers from conflicts between third party dependencies, as well as conflicts between dependencies of our third party dependencies.

We build the codebase with enabled property AutoGenerateBindingRedirects. (See https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection). This ease conflict management for building & running our test projects.

With reasons, we do not force nu to _automatically_ solve version conflicts with binding redirects. In my opinion automated binding redirects this is rather an antipattern. I prefer fixing conflicts on compile time, or well thought on runtime; instead of automated direction to potential other assembly versions that my unit tests are using. 
We want to be in control of our dependency conflict resolution by updating them manually, in order to reduce or raise our awareness on potential bugs that are introduced by resolving conflicts automatically by nuget.

**Comment by BrennanConroy** [comment]
Triage: We should verify that binding redirects are added when using a .NET Framework app with a 3.1.8 version of an Extensions package.

**Comment by BrennanConroy** [comment]
Confirmed.
