### ISSUE TITLE
QUESTION - ActivatorUtilities.CreateInstance<> not working same as IServiceProvider.GetService<> when injecting HttpClient

### ISSUE THREAD

**Issue by SOHODeveloper** [dotnet/extensions#3396]
### Describe the bug
IServiceProvider.GetService honors Typed Creation of an HttpClient, but ActivatorUtilities does not.
I am asking if this is expected behavior.  If so I would like an explanation so that I may understand the issue.  If not expected, I will create a repro. 

### To Reproduce
Using .net core 5.0 preview 7 (note the .net info output says SDK is preview 6, but all nuget packages are preview 7)
Register the following
```
serviceCollection.AddHttpClient<SendGridClientValidation>((c) =>
{
    c.BaseAddress = new Uri("https://api.sendgrid.com/v3/");
});
serviceCollection.TryAddTransient<SendGridClientValidation>();  // i have tried both Transient and Singleton here

```
Use `ActivatorUtilities.CreateInstance<SendGridClientValidation>(services, "this is a string");`
in this case the BaseAddress is not set, but a HttpClient is injected.

Remove the string parameter from SendGridClientValidation constructor and use
`services.GetRequiredService<SendGridClientValidation>` and the injected HttpClient has the correct base address.

### Expected behavior
I expected both methods to result in a HttpClient with the BaseAddress set.

### Additional context
Include the output of `dotnet --info` - Attached
[info.txt](https://github.com/dotnet/extensions/files/5059155/info.txt)

**Comment by Pilchie** [comment]
Tagging @karelz - this is another HttpClientFactory issue.

**Comment by Pilchie** [comment]
@SOHODeveloper why do you have both `AddHttpClient` and `TryAddSingleton`?  `AddHttpClient` should add it to DI?

**Comment by SOHODeveloper** [comment]
Are you saying that
serviceCollection.AddHttpClient<SendGridClientValidation>((c) =>
{
    c.BaseAddress = new Uri("https://api.sendgrid.com/v3/");
});
Registers SendGridClientValidation in DI instead of just registering the factory to be used with it?

**Comment by Pilchie** [comment]
Tagging @davidfowl for some context here.  I don't actually have enough context on `ActivatorUtilities` to know what's expected in this case.

**Comment by BrennanConroy** [comment]
ActivatorUtilities will create an instance of your object, it will not run any sort of configuration methods that the DI methods set up for you.

**Comment by SOHODeveloper** [comment]
@BrennanConroy  That action seems very wrong.
@Plichie, @davidfowl  Still wondering if the call to AddHttpClient registers both the client and the factory

**Comment by halter73** [comment]
To be more specific, ActivatorUtilities does not run the service factory that defines SendGridClientValidation. It's impossible for ActivatorUtilities to run the SendGridClientValidation service factory, because that factory does not accept any extra arguments such as the "this is a string" argument you are trying to provide. ActiviatorUtilities still resolves dependencies from the specified ServiceProvider, and those dependencies will be configured normally.

Since AddHttpClient does register `TClient` (which is SendGridClientValidation in this case) using a service factory instead of using the default constructor discovery logic, you'll need to re-implement the service factory logic to create a `TClient` using ActivatorUtilities. You can see how the service factory is defined below:

```C#
            builder.Services.AddTransient<TClient>(s =>
            {
                IHttpClientFactory httpClientFactory = s.GetRequiredService<IHttpClientFactory>();
                HttpClient httpClient = httpClientFactory.CreateClient(builder.Name);

                ITypedHttpClientFactory<TImplementation> typedClientFactory = s.GetRequiredService<ITypedHttpClientFactory<TImplementation>>();
                return typedClientFactory.CreateClient(httpClient);
            });
```

https://github.com/dotnet/runtime/blob/254ef0f7f7f429ec238735fe6132805e3c38a19f/src/libraries/Microsoft.Extensions.Http/src/DependencyInjection/HttpClientBuilderExtensions.cs#L401-L408

In the case of SendGridClientValidation, the default `builder.Name` should just be "SendGridClientValidation", but `builder.Name` can be configured with the [AddHttpClient overloades](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.httpclientfactoryservicecollectionextensions.addhttpclient?view=dotnet-plat-ext-3.1#Microsoft_Extensions_DependencyInjection_HttpClientFactoryServiceCollectionExtensions_AddHttpClient__2_Microsoft_Extensions_DependencyInjection_IServiceCollection_System_String_System_Action_System_IServiceProvider_System_Net_Http_HttpClient__) that take a `name` parameter. I haven't tested it, but the following should give you the behavior you want.

```C#
// I haven't actually tested this, but I expect it will work.
IHttpClientFactory httpClientFactory = s.GetRequiredService<IHttpClientFactory>();
HttpClient httpClient = httpClientFactory.CreateClient("SendGridClientValidation");

// The following is more-or-less all the default ITypedHttpClientFactory does.
// The only reason we don't use the ITypedHttpClientFactory is because it doesn't take extra parameters.
ActivatorUtilities.CreateInstance<SendGridClientValidation>(services, httpClient, "this is a string");
```

You can find the default ITypedHttpClientFactory at https://github.com/dotnet/runtime/blob/254ef0f7f7f429ec238735fe6132805e3c38a19f/src/libraries/Microsoft.Extensions.Http/src/DefaultTypedHttpClientFactory.cs. You can see it uses ActivatorUtilities itself internally.

**Comment by SOHODeveloper** [comment]
@halter73 - Thanks much for the detailed information.  I need to take some time to absorb it and understand how to use it correctly.
