### ISSUE TITLE
LoggingScope not disposed properly during async/await operation

### ISSUE THREAD

**Issue by Doomblaster** [dotnet/extensions#3412]
I've implemented an IClientInspector to do some logging right before and right after we do a WCF call. Before logging we start a scope, and disposing that scope after we've received an answer. When using the WCF client, generated by dotnet-svcutil, the scope doesn't go away between calls IF we use async methods on the client. If we use the sync methods it works as expected. I have a sneaky feeling I'm doing something wrong, but I can't really pinpoint it though.

Synchronous
![image](https://user-images.githubusercontent.com/1055547/90390531-c2b5ed00-e08b-11ea-9b84-9fec9f928cb6.png)
Asynchronous
![image](https://user-images.githubusercontent.com/1055547/90390558-d6f9ea00-e08b-11ea-894e-7120bda71596.png)

### To Reproduce
See attached repro
[WCFRepro.zip](https://github.com/dotnet/extensions/files/5083900/WCFRepro.zip)

### Expected behavior
I would expect this to work the same way for both sync and async

**Comment by KalleOlaviNiemitalo** [comment]
LoggerExternalScopeProvider keeps the linked list of scopes in an AsyncLocal whose value will not flow from inner async functions to outer. <https://github.com/dotnet/extensions/blob/784b0ffaa40779255758ebbb146334da489a4bde/src/Logging/Logging.Abstractions/src/LoggerExternalScopeProvider.cs#L14>

For Dispose to close the scope properly, it has to be called in the same async function that created the scope. However, I doubt it is possible to do that with WCF IClientMessageInspector.

Perhaps you could instead implement IRequestChannel.BeginRequest by calling an async method that opens the logging scope, calls innerChannel.BeginRequest, wraps the IAsyncResult to a Task ([Tasks and the Asynchronous Programming Model (APM)](<https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/interop-with-other-asynchronous-patterns-and-types#APM> "Interop with Other Asynchronous Patterns and Types | Microsoft Docs"), awaits that Task, and closes the logging scope. The Task from that async method would then have to be transformed back to an IAsyncResult with the correct IAsyncResult.AsyncState so that IRequestChannel.BeginRequest could return it.

**Comment by KalleOlaviNiemitalo** [comment]
<https://github.com/dotnet/wcf/issues/3491#issuecomment-485047454> mentions a NuGet package that implements IClientMessageInspector as a wrapper for a delegate that returns `Task<Message>`. If that delegate refers to an async method, then it will be able to open and close the logging scope properly. If that async method logs the "Before request" and "After request" events, then those should also get attached to the logging scope just fine. However, if the WCF channel also logs some events, I don't think they can be attached to the logging scope.

**Comment by davidfowl** [comment]
This needs to be fixed by WCF itself. Your logging provider shouldn't leak the execution context outside of those calls anyways, that's the issue to fix here. IT would also be nice to expose something more async friendly as logging scopes aren't the first or last things that will use async locals (Activity also comes to mind).

The easy fix for your code to wrap async calls in an async method:

```C#
{
            logger.LogInformation("Running asynchronous");
            result = await AddAsync(client, 1, 2);
            logger.LogInformation($"Result {result}");
            result = await AddAsync(client, 2, 3);
            logger.LogInformation($"Result {result}");
            result = await AddAsync(client, 3, 4);
            logger.LogInformation($"Result {result}");
            result = await AddAsync(client, 4, 5);
            logger.LogInformation($"Result {result}");

            Console.WriteLine("Press any key to exit");
            Console.ReadKey();
        }

        private static async Task<int> AddAsync(ICalculatorChannel client, int x, int y)
        {
            return await client.AddAsync(x, y);
        }
```

Notice the AddAsync method at the bottom that wraps the `ICalculatorChannel` and forces the method to use async await. This will force exiting the call to restore the original execution context thus reverting all async locals and the logging scopes.

**Comment by KalleOlaviNiemitalo** [comment]
@davidfowl, does WCF ensure that the AsyncLocal value will flow from IClientMessageInspector.BeforeSendRequest to IClientMessageInspector.AfterReceiveReply, so that the "After request" entry logged by AfterReceiveReply will have the logger scope that BeforeSendRequest began? From the screen shots, it looks like the value flowed in the test, but I am not sure that will always happen.

**Comment by Doomblaster** [comment]
At least the nuget @KalleOlaviNiemitalo  mentions in https://github.com/dotnet/extensions/issues/3412#issuecomment-675932310 solves the issue.
As for the other solutions, I guess they also could work, but the point is to have some reusable component that we can distribute between different projects, hence plugging in to the traditional extensionpoints in WCF seems like the best way to do it.

**Comment by KalleOlaviNiemitalo** [comment]
Perhaps <https://github.com/dotnet/runtime/issues/36090> could solve this in a different way. Let the app provide IExternalScopeProvider and implement IExternalScopeProvider.ForEachScope so it reads the activity info from WCF and generates a scope for that. Problems:

- DiagnosticUtility.ShouldUseActivity seems to be always false for .NET Core, so ServiceModelActivity.Current would remain null.
- I'm not sure OperationContext.Current is valid during IClientMessageInspector. I know it is not reliable during IDispatchOperationSelector in WCF server.
- TraceSourceLogger cannot implement ISupportExternalScope, because TraceEventCache.LogicalOperationStack reads Trace.CorrelationManager.LogicalOperationStack.

I don't think there is anything else that can be done in dotnet/extensions to help with WCF.

**Comment by BrennanConroy** [comment]
cc @mconnew

Closing as it looks like a WCF issue

**Comment by mconnew** [comment]
@KalleOlaviNiemitalo, While I haven't made changes to ServiceModelActivity.Current, I've made other changes needed for our ETW EventSource in our current preview release which might provide what's needed. The commit with the changes is [here](https://github.com/dotnet/wcf/commit/702122315ba4e83a18afd039345cd34e7cd6e21e). This was a targeted fix for when logging ETW events and using the CorrelationManager to get the ActivityId and creating transfer events. If there are other usage scenarios, I'm definitely open to enabling them, I just need an example.  
The problem we have is we had to make lots of changes to accommodate everything we depended on being yanked in early versions of .NET Core. Then it was decided to bring it all back (well, most of it) and there wasn't a central place listing everything that got brought back. We also have dependencies on things which we can't use anymore so some features can't be enabled easily even now. So I'm fixing/re-adding things as they become blockers for people. Also FYI OperationContext.Current hasn't been set yet in `IDispatchOperatonSelector.SelectOperation` because you can't create an **Operation**Context until you are starting the operation which can't start until you know which operation has been called. I think it's the only dispatcher extensibility point where the OperationContext.Current isn't valid as we create it immediately after the SelectOperation call.  

@Doomblaster, feel free to open an issue on dotnet/wcf and reference this one. It's odd that the workaround provided by @davidfowl works as we provide a TaskCompletionSource.Task for you to await on. The only thing I can think of is things are being modified before we return the Task, the synchronous code before going async,
