### ISSUE TITLE
Remove Frequency from Latency structs

### ISSUE THREAD

**Issue by danmoseley** [dotnet/extensions#3998]
We are storing the TimeProvider.TimestampFrequency in every LatencyData and Checkpoint. (We store it separately in order to defer doing math.)

https://github.com/dotnet/extensions/blob/e93439fc5f6ce14a27795bc63a99c0dbf182e448/src/Libraries/Microsoft.Extensions.Telemetry.Abstractions/Latency/LatencyData.cs#L27
https://github.com/dotnet/extensions/blob/e93439fc5f6ce14a27795bc63a99c0dbf182e448/src/Libraries/Microsoft.Extensions.Telemetry.Abstractions/Latency/Checkpoint.cs#L24

This frequency does not change after the system started. It can be different between systems, though, so we should not store it, but pass it when exporting/importing.

**Comment by andrey-noskov** [comment]
The main benefit of this type is that it allows to remove all hardcodes related to time sources and enables service owners to use whatever clock source they want with any characteristics they need. This implies that API must be adapted to work well in the cases when (1) there is more than one time-provider within the same process, (2) time providers might use sources with different frequencies.
This is NOT to state that service owners will immediately start to use the features above but given that this functionality is offered in the form of an injectable and overridable interface, I believe we must assume the configuration above and so the API surface must keep the bar high.

We used to have a dedicated type in 1P impl specifically to carry the frequency and timestamp in one struct. This provided lots of benefits compared to the current loose model with the tuple. Can we return it back?

**Comment by danmoseley** [comment]
Just because it is possible, does not of course mean it cannot  be advised against. We could simply say: timestamps from different providers cannot be mixed, or in such cases one must do the math (that is normally deferred due to cost/truncation). 

After all, if we believe this is an important scenario and these will get passed around in arbitrary ways, we should consider proposing a first class { timestamp, frequency } structure. TimeProvider (and Stopwatch before it) is arguably leaking implementation details by providing these separately. Consumers don't care about what they are individually -- they are supposed to be opaque, allowing you to get relative ordering while deferring the more expensive calculation of absolute time interval.

Such a structure would presumably be TimeSpan, with TicksPerMicrosecond now being derived from Frequency rather than constant. (It would make TimeSpans larger size)

**Comment by danmoseley** [comment]
cc @dotnet/area-system-datetime

**Comment by andrey-noskov** [comment]
cc @geeknoid

**Comment by tarekgh** [comment]
> @tarekgh was this use case considered during design of TimeProvider?

This has been discussed in the gist https://gist.github.com/tarekgh/dfea6aa07833c2dcecd8c2e98ff18e19?permalink_comment_id=4493730#gistcomment-4493730. Users can just use value tuple to store the timestamp and the frequency as needed.

**Comment by geeknoid** [comment]
In a testing environment, it will be common for there to be two distinct time providers in use. The component under test will be using the FakeTimeProvider, while other components may use the TimeProvider.System. This can lead to checkspoints at different frequencies colliding in the latency infra.

Like @andrey-noskov, I definitely miss the PerfTimeSpan struct we used in 1P for this stuff which carried both the frequency and timestamp. It is cleaner to use in the code by having one thing umambiguously representing an amount of time, as opposed to have two lose `long` values. But I lost that battle already...

**Comment by danmoseley** [comment]
Hmm, I see. In that case, mightn't it be better to for me to set the FakeTimeProvider.Frequency to whatever the value of TimeProvider.System.Frequency?

As it is, whether there's a custom struct or not, this is complicating the product code (passing structs instead of longs) everywhere with no benefit in production.

**Comment by geeknoid** [comment]
At the end of the day, the checkpoint and latency timestamps are normalized on output, so we could normalize on input in order to store less data.

**Comment by danmoseley** [comment]
Yes, at the expense of a division/multiplication and possibly a loss of a bit of precision vs first subtracting timestamps and then applying the frequency. (Essentially the reasons why frequency is exposed in the first place.).

**Comment by andrey-noskov** [comment]
@danmoseley , what benefits do you see in using longs as opposed structs?
I am a big fan of strong types and as a customer of the SDK, I would prefer this value to be represented in the form of a strong type because the value has some context, has some meaning and rules associated with how the value is supposed to be used - such approach not only enables me (the customer) to write somewhat cleaner code (compare a method that accepts an arbitrary long where the expectations for the long value defined in xml comments only with the case where the same method accepts PerfTimeSpan with compiler performing type checking at compile time), but also allows us (the SDK owners) to contain some logic within the type and me (again the customer) to write handy external extensions for it.

**Comment by danmoseley** [comment]
Would need new API on TimeProvider and presumably Stopwatch?

But I think it is better for date/time owners to weigh in.

Note this would be a non breaking change to do later.

**Comment by stephentoub** [comment]
The PerfTimeSpan was broken for its purpose.  Just the timestamp value and frequency value are insufficient to enable comparison with any other PerfTimeSpan, because you don't know that the basis of the providers from which they came is the same.  You can't compare across providers without that information, e.g. one might ticks since startup and another might be ticks since the epoch.  And since you can get the frequency from the provider, at that point you could have a struct that wrapped the timestamp and the provider, but even then there's nothing you can do with just that instance.  An individual TimeSpan or DateTime instance is meaningful, but there's nothing meaningful about a single PerfTimeSpan... you need to compare it with something else and something else from the same provider for it to be meaningful.  At that point the only benefit to carrying around the provider reference is to be able to throw an exception if you compared it with one from a different provider, and for a system that rails on peanut butter, that's fairly significant peanut butter: every async state machine, every object, etc. in which you store one of these is now carrying around an extra reference field just to store that provider reference.  So then you're at the point where the struct is simply there to put a strongly-typed name on a long value that can't be used on its own, so it's not even as good as a unit-of-measure feature.  This all leads us to just leaving it as a long.

**Comment by rafal-mz** [comment]
Isn't provider a singleton in the design? I.e, do we expect multiple time providers to live within the same app? I thought that we've made this type for measuring time with high resolution. These types were not designed to be used for calculation outside of single application boundary.

**Comment by stephentoub** [comment]
> Isn't provider a singleton in the design

TimeProvider.Default is a singleton, but TimeProvider in general is an abstraction, of which any number of concrete derived types and instances of those types could be constructed, injected via DI, etc.

**Comment by geeknoid** [comment]
> The PerfTimeSpan was broken for its purpose. Just the timestamp value and frequency value are insufficient to enable comparison with any other PerfTimeSpan, because you don't know that the basis of the providers from which they came is the same.

Our assumption was a common universal epoch, matching that of TimeSpan.

**Comment by geeknoid** [comment]
An alternate design was a PerfTimeSpan which contains a tick value and a reference to the TimeProvider it originates from. I originally decided to stick the provider's frequency in PerfTimeSpan instead of the provider instance because it was sufficient and reduced the number of references being written to the heap (to avoid card table writes)

**Comment by stephentoub** [comment]
> Our assumption was a common universal epoch, matching that of TimeSpan.

I don't know what that means.  What is TimeSpan's epoch, and, for example, how does Stopwatch.GetTimestamp's relate to that?  The old FakeClock and SystemClock did not have the same epoch (one was based on Stopwatch, which is not time since Jan 1, 0001, and one on DateTime.UtcNow, which is).  Stopwatch.GetTimestamp itself can have different epochs based on which timer mechanism is used under the covers.

**Comment by geeknoid** [comment]
Sorry, I confused myself about epochs.

If I have a PerfTimeSpan with a tick count and a frequency, and another PerfTimeSpan with a tick count and a frequency, I don't understand your assertion that this was broken and didn't allow comparisons. In absolute terms, they both represent an absolute amount of time and so can be compared to one another.

**Comment by stephentoub** [comment]
> In absolute terms, they both represent an absolute amount of time and so can be compared to one another.

No, they don't, they each represent a period of time since their respective epoch. For simplicity let's say frequency is 1 across the board.  I then have a value of 100 seconds from one time provider and a value of 200 seconds from another time provider.  If both time providers have the same epoch, then they're 100 seconds apart.  But if one time provider's epoch is Jan 1, 0001 and the other's is Jan 1, 1970, the difference between Jan 1, 0001 + 100 seconds and Jan 1, 1970 + 200 seconds is now measured in millenia, not seconds.

**Comment by tarekgh** [comment]
The file systems on Linux and Windows have a different epochs but internally we normalize the ticks when using it inside our types like DateTime[Offset]. But in general, if there is anyone creating a custom PerfTimeSpan they may run into what @stephentoub is describing here. In .NET we always expose the ticks starting from `1/1/1:0:0:0`.

**Comment by stephentoub** [comment]
> internally we normalize the ticks when using it inside our types like DateTime[Offset]

For DateTime{Offset}, not for Stopwatch.GetTimestamp.

**Comment by tarekgh** [comment]
Right, Stopwatch.GetTimestamp will depend on the underlying system epoch.

**Comment by geeknoid** [comment]
@stephentoub I really don't understand how time providers have anything to do with PerfTimeSpan.

A PerfTimeSpan contained a tick count and a frequency. This represents a total amount of time, independent of epoch:

1000 ticks at 1000Hz == 1 seconds
1 tick at 1Hz == 1 seconds

0 ticks at 1000Hz = 0 seconds
0 ticks at 1Hz = 0 seconds

This is not relative to any epoch, it is an absolute measurement of a quantity of time.

R9 also had a PerfTime value. The tick count carried by this struct was relative to an epoch. The tick value there thus represents a relative amount of time to the epoch.
