### ISSUE TITLE
Rename `Microsoft.AspNetCore.Testing`

### ISSUE THREAD

**Issue by RussKie** [dotnet/extensions#4057]
ASP.NET Core ships `Microsoft.AspNetCore.Testing` and has been doing so for years. We must rename our package.

Related: https://github.com/dotnet/dnceng/issues/174

**Comment by RussKie** [comment]
@joperezr @geeknoid what are the plans for this? We need this library for the R9 upgrade.

**Comment by joperezr** [comment]
We talked about this today. As explained, the issue is that even though the package doesn't show up in nuget.org, it is because it is de-listed but the package does exist. The conclusion from our discussion today was that we will force push the package from extensions using Microsoft.AspNetCore.Testing name, and we will log an issue on aspnetcore repo to rename the assembly there (given it is internal only and contains types that are not to be exposed publicly anyway)

**Comment by RussKie** [comment]
The aspnetcore's package must not be published to the BAR either, as we can't publish our the package.

**Comment by RussKie** [comment]
@Tratcher @wtgodbe @epananth I'm reverting https://github.com/dotnet/extensions/pull/4058, and our Microsoft.AspNetCore.Testing will again be published to the BAR.
