### ISSUE TITLE
Reference latest libraries packages

### ISSUE THREAD

**Issue by ericstj** [dotnet/extensions#4098]
This repo is already doing a pretty good job of referencing the latest packages, but I noticed a few places that this could be improved.  @ViktorHofer might be able to spot more.

I'd like to understand why you're referencing older versions of the following packages.  I think the latest version from 8.0 should work everywhere.
https://github.com/dotnet/extensions/blob/e72de4cfeb1a2917694b96d0eaaabdc4e8b81478/eng/Packages/General-net462.props#L9
https://github.com/dotnet/extensions/blob/e72de4cfeb1a2917694b96d0eaaabdc4e8b81478/eng/Packages/General-net462.props#L14
https://github.com/dotnet/extensions/blob/e72de4cfeb1a2917694b96d0eaaabdc4e8b81478/eng/Packages/General-net462.props#L17
https://github.com/dotnet/extensions/blob/e72de4cfeb1a2917694b96d0eaaabdc4e8b81478/eng/Packages/General-net462.props#L19

This package reference should be avoided, so long as nothing else brings it in. 
https://github.com/dotnet/extensions/blob/e72de4cfeb1a2917694b96d0eaaabdc4e8b81478/eng/Packages/General-net462.props#L20
The following can be removed if you target at least .NET 4.7 and nothing else brings it in -- ~~4.6.2 is out of support.~~
https://github.com/dotnet/extensions/blob/e72de4cfeb1a2917694b96d0eaaabdc4e8b81478/eng/Packages/General-net462.props#L23

This doesn't appear to be used anywhere and should be removed.
https://github.com/dotnet/extensions/blob/e72de4cfeb1a2917694b96d0eaaabdc4e8b81478/eng/Packages/General-netcoreapp3.1.props#L15

**Comment by RussKie** [comment]
> The following can be removed if you target at least .NET 4.7 and nothing else brings it in -- 4.6.2 is out of support.

@ScottThurlow @geeknoid do we have 1P consumers on net462? Can we bump to net472?

**Comment by ViktorHofer** [comment]
According to my source, net462 isn't out of support.

**Comment by geeknoid** [comment]
@ericstj This repo started out with graduated versioning. That is, the net462 TFM was depending on older versions of M.E.Extensions, the netcoreapp3.1 TFM was depending on 3.3 extensions, the net5.0 TFM was depending on 5.0 extensions, etc. This was so in order to avoid customers consuming some specific TFM to have their transitive dependencies on extensions be automatically uplevels on them. This was important due to the compat issues between different versions of the extensions over time (uplevels are bad when that breaks customer builds, of course).

Once code in this repo started to take dependencies on .NET 8 features in the extensions, we had to start giving up on the graduated dependency version thing. And now that the .NET 8 extensions are retroactively fixing the majority of breaking changes in the extensions, it's time to completely ditch the whole idea.

I'll make a pass to clean all this up.

**Comment by ericstj** [comment]
> According to my sources, net462 isn't out of support.

My mistake for trusting bing ☹️ 
<img width="331" alt="image" src="https://github.com/dotnet/extensions/assets/8918108/b703e79c-edf9-4b44-b5ed-2151cbd3d1cc">

Looks like it remains supported [until January 2027](https://learn.microsoft.com/en-us/lifecycle/products/microsoft-net-framework), so System.ValueTuple cannot be removed yet.

> I'll make a pass to clean all this up.

Let me know if we find any unique problems with moving up the remaining dependencies and we can look into them.
