### ISSUE TITLE
Update IEnrichmentPropertyBag to use spans

### ISSUE THREAD

**Issue by klauco** [dotnet/extensions#4208]
Update the IEnrichmentPropertyBag interface to be more efficient using spans.

**Comment by dariusclay** [comment]
Looks like this one is already handled @klauco. #4239

Can you confirm and close?

**Comment by geeknoid** [comment]
Let's change this work. Instead of dealing with spans, I think we should just simplify this interface to have a single method on it which is Add(string, object), and that's all. This will let us simplify a bunch of enrichment logic throughout the code base. The idea of using spans in the interface is no longer meaningful due to the addition of IStaticLogEnricher which offloads processing to startup time, instead of being invoked for every log record.
