### ISSUE TITLE
HttpClient logging doesn't log path parameters in Structured mode

### ISSUE THREAD

**Issue by xakep139** [dotnet/extensions#4698]
Consider this example:
```cs
var builder = Host.CreateApplicationBuilder(args);

builder.Logging.AddJsonConsole();

builder.Services.AddRedaction();

builder.Services.AddExtendedHttpClientLogging(options =>
{
    options.RequestPathLoggingMode = OutgoingPathLoggingMode.Structured;
    options.RequestPathParameterRedactionMode = HttpRouteParameterRedactionMode.Loose;
});

var host = builder.Build();

var httpClientFactory = host.Services.GetRequiredService<IHttpClientFactory>();
using var httpClient = httpClientFactory.CreateClient();

using var requestMessage = new HttpRequestMessage(HttpMethod.Get, "https://api.github.com/users/aspnet/repos");
var requestMetadata = new RequestMetadata()
{
    RequestRoute = "users/{userId}/repos",
    DependencyName = "GitHub",
    RequestName = "Get user repos"
};

requestMessage.SetRequestMetadata(requestMetadata);
using var response = await httpClient.SendAsync(requestMessage);
```

That way you don't have a chance to see the value of `userId` path parameter in logs. The same `RequestPathLoggingMode` applied in incoming HTTP logging emits path parameters as separate tags.
Is it a bug?

**Comment by xakep139** [comment]
cc @klauco @iliar-turdushev @dariusclay @omsoftdev

**Comment by iliar-turdushev** [comment]
> That way you don't have a chance to see the value of `userId` path parameter in logs.

I didn't get this. As I understand, when you set `RequestPathLoggingMode=Structured` route parameters are emitted as individual log attributes, and IMO such behavior is intentional. Here is a screenshot showing how  `RequestPathLoggingMode=Structured` works for HttpLogging:

![image](https://github.com/dotnet/extensions/assets/10431021/594c7a01-240d-479f-b680-a26526c07756)

It outputs `Path` as http route, and route parameters as individual attributes. Everything is in place. Or am I missing something?

**Comment by xakep139** [comment]
Correct, it works for incoming HTTP logging, but doesn't work for outgoing logging
