### ISSUE TITLE
READMEs are not rendered on NuGet.org

### ISSUE THREAD

**Issue by sebastienros** [dotnet/extensions#4722]
Source for the metadata: https://github.com/dotnet/extensions/blob/release/8.0/src/Directory.Build.props#L12-L14

Using Package Explorer we can confirm that the `<readme>` tag is missing.
Example: https://nuget.info/packages/Microsoft.Extensions.Diagnostics.ExceptionSummarization/8.0.0

Details for npgsql:

```xml
   <icon>postgresql.png</icon>
    <readme>README.md</readme>
    <projectUrl>https://github.com/npgsql/npgsql</projectUrl>
    <description>Npgsql is the open source .NET data provider for PostgreSQL.</description>
```

and for `Microsoft.Extensions.Diagnostics.ExceptionSummarization`

```xml
    <icon>Icon.png</icon>
    <projectUrl>https://dot.net/</projectUrl>
    <description>Lets you retrieve exception summary information.</description>
```

However, the README file is available in the package at the expected location.

**Comment by RussKie** [comment]
@Tratcher tracked the regression down to https://github.com/dotnet/extensions/pull/4562...

**Comment by RussKie** [comment]
I've looked at the [latest official build artifacts](https://dev.azure.com/dnceng/internal/_build/results?buildId=2319115&view=artifacts&pathAsName=false&type=publishedArtifacts) and the readmes are there...

![image](https://github.com/dotnet/extensions/assets/4403806/befc1750-1bf2-4250-b06b-1185ffd96132)

 What am I missing?

**Comment by joperezr** [comment]
README's have always been there 😃. The issue is not that, but instead the problem is that the metadata in the nuspec is not set correctly causing the README to not be surfaced by nuget.org. As @Tratcher pointed out 2 weeks ago, I think the issue is in this condition:

https://github.com/dotnet/extensions/blob/13a6288c9de8d8f83c40ae419803e6a990bf5825/src/Directory.Build.props#L12C1-L14

As I think there is an ordering problem where one of those two properties in the condition isn't set yet, causing that Property (PackageReadmeFile) to not be set. The reason why the README is still on the package even though the exact same condition is used in the same file in order to add the file to the package, is only because of how MSBuild always evaluates all properties (and propertyGroups) first in the initial evaluation pass, and then does the Items and ItemGroups.

**Comment by RussKie** [comment]
Got it, thank you for explaining it (again).
