### ISSUE TITLE
Release of M.E.Hosting.Testing

### ISSUE THREAD

**Issue by galakt** [dotnet/extensions#4809]
As far as I see there is only pre-release version of this package (https://www.nuget.org/packages/Microsoft.Extensions.Hosting.Testing/8.0.0-rtm.23558.11)

When do you plan to release a stable version?

**Comment by geeknoid** [comment]
I'm hoping we can get this finalized in January.

**Comment by geeknoid** [comment]
Since this is not actually an issue, closing...

**Comment by xakep139** [comment]
@galakt just to explain: the package is in `dev` stage, that's why it won't have a stable version until we move it to `normal` stage.
The stage is defined in https://github.com/dotnet/extensions/blob/9d2a631e891b015070280b386534f676ed14e408/src/Libraries/Microsoft.Extensions.Hosting.Testing/Directory.Build.props#L6
