### ISSUE TITLE
Issue between JustInTimeRedactor and OpenTelemetry OTLP batch exporter

### ISSUE THREAD

**Issue by NatMarchand** [dotnet/extensions#5080]
### Description

Opening a bug in this repo as suggested here : https://github.com/open-telemetry/opentelemetry-dotnet/issues/5276#issuecomment-1956941967

When using redactors with OpenTelemetryExporter and batch, JustInTimeRedactor values are returned to the pool before log record is sent. Therefore, when sending we get a NullReferenceException while reading value (which is caught by the lib) leading to the attribute not sent.

### Reproduction Steps

See repro project and original issue.
https://github.com/NatMarchand/repro-dotnet-log-redactor/blob/main/ConsoleApp1/Program.cs

### Expected behavior

The attribute with the redacted value is sent to my otel collector redacted

### Actual behavior

The attribute with the redacted value is not sent to my otel collector.

### Known Workarounds

A BaseProcessor which "freeze" IResettable values
```
public class FreezePooledValuesProcessor : BaseProcessor<LogRecord>
{
    public override void OnStart(LogRecord data)
    {
        base.OnStart(data);
    }

    public override void OnEnd(LogRecord data)
    {
        if (data.Attributes is not null)
        {
            data.Attributes = data.Attributes
                .Select(kvp => kvp.Value is IResettable resettable ? KeyValuePair.Create<string, object?>(kvp.Key, resettable.ToString()) : kvp)
                .ToList();
        }

        base.OnEnd(data);
    }
}
```
However, as data.Attributes is a read only collection we must replace the whole collection iterating through every object and replacing IResettable.

**Comment by joperezr** [comment]
cc @geeknoid. Thanks for the report @NatMarchand. If I remember correctly, we had already seen this issue, and at the time we believed the issue was actually with OTel as they were calling ToString again which is where the NullRef was happening. I think @geeknoid mentioned that OTel shouldn't assume that it was safe to call ToString

**Comment by geeknoid** [comment]
Indeed, otel in this regard. It is calling ToString on an object after the call to ILogger.Log returns, which is definitely against the contractual expectation of ILogger.Log. You don't expect some function to hold on to object references and call into these objects at a random time later in time. No only can this lead to the kind of issue you're seeing here, it can also lead to just plain crashes since the objects in question aren't necessarily designed for being called asynchronously.

So I'm closing this issue, it's an otel bug.

**Comment by NatMarchand** [comment]
> @NatMarchand I was under the impression that we had already logged a bug in OTel for this and wanted to close this and point to that, but it doesn’t look like we have done that, apologies. I will log a bug with detail information and include some of the details you shared, and will link it to here.

Unless you have an internal bug tracker, it is already logged :)
https://github.com/open-telemetry/opentelemetry-dotnet/issues/5276

**Comment by joperezr** [comment]
Oh, awesome, somehow I couldn't find that for some reason. Thanks a bunch @NatMarchand! We will definitely follow the development of that one, and happy to +1 it and provide context if needed.
