### ISSUE TITLE
[API Proposal]: Logging source generator: support template customization

### ISSUE THREAD

**Issue by Micke3rd** [dotnet/extensions#5223]
### Background and motivation

1. There are parameters that you want to determine in many log functions. Instead of manually maintaining repetitive code in each method marked with [LoggerMessage], these parts should be moveable to the generator. Example:
```
[LoggerMessage(LogLevel.Information)]
internal static partial void ExampleA(ILogger logger, Person person
		, [CallerMemberName] string SourceMemberName = ""                    --> repetitive
		, [CallerFilePath] string SourceFilePath = ""                         --> repetitive
		, [CallerLineNumber] int SourceLineNumber = 0                          --> repetitive
		);
```

2. Customizable template would allow TState to be filled with customized logic.
This includes the use of serializers that are not limited to [LogProperties]. This is already possible by overriding ToString() in the respective classes, but since these data structures are usually created for the respective log method, this overload must be created accordingly often. Example:
```
readonly record struct Person(uint Id, string Name, Person[]? Parents = null)
{
	public override string ToString() => JsonSerializer.Serialize(this);
}
```

### API Proposal

no instructions on how to access, the main thing is somehow

### Risks

no known risks

thank you for reading

**Comment by tarekgh** [comment]
Moving it to extensions repo as more replated to advanced features like LogProperties. 

CC @geeknoid

**Comment by geeknoid** [comment]
> > Serializing an object as json to put it in the log like your code does is a really bad way to do it
> 
> Why ? The JsonSerialization in the example symbolizes logging for the purpose of later machine processing. [LogProperties] only serializes the first level, which is not always sufficient.

[LogProperties] can be applied to properties in your objects. With this, you can log tranaitively full graphs of objects.

**Comment by geeknoid** [comment]
@Micke3rd Hey there, I'm sorry but I don't actually understand what you're suggesting/asking. Could you please provide an example of what you'd like to see?

**Comment by geeknoid** [comment]
Unfortunately, it's not that simple. Basically what you're asking for is to mostly write a new logging generator, since the emitter is most of what a generator is about. If you look around in the code base, you'll see that there is a lot of logic to support the generation of the source code.

Stepping away from the implementation of emitters, is the behavior you're looking for as a user is to be able to tell the generator to inject a specific set of parameters on all the logging methods? Can you come up with an example that shows what you would like to write in your source code, and what you would like to have the generator produce as output?
