### ISSUE TITLE
[API Proposal]: Streaming methods for IEmbeddingGenerator

### ISSUE THREAD

**Issue by azchohfi** [dotnet/extensions#5548]
### Background and motivation

The IEmbeddingGenerator interface doesn't support streaming, which makes sense mostly with batching (for remote/cloud implementations) or with local embeddings models, that runs much slower in the CPU, for example.

### API Proposal

```csharp
namespace System.Collections.Generic;

public class LocalEmbeddingGenerator : IEmbeddingGenerator<string, Embedding<float>>
{
  public async IAsyncEnumerable<Embedding<float>> GenerateStreamingAsync(
      IEnumerable<string> values,
      EmbeddingGenerationOptions? options = null,
      [EnumeratorCancellation] CancellationToken cancellationToken = default)
  {
      int chunkSize = 128;
  
      var chunks = values.Chunk(chunkSize);
  
      foreach (var chunk in chunks)
      {
          cancellationToken.ThrowIfCancellationRequested();
  
          GeneratedEmbeddings<Embedding<float>> embeddings = await GenerateAsync(chunk, options, cancellationToken).ConfigureAwait(false);
  
          foreach (var embedding in embeddings)
          {
              cancellationToken.ThrowIfCancellationRequested();
  
              yield return embedding;
          }
      }
  }
...
}
```

### API Usage

```csharp
IEmbeddingGenerator<string, Embedding<float>> localEmbeddings = new LocalEmbeddingGenerator();
await foreach (var embedding in localEmbeddings.GenerateStreamingAsync(largeEnumerable, null, cts.Token))
{
   ...
}
```

### Alternative Designs

Such method is likely going to be similar between different implementations, so maybe an extension method would suffice.

### Risks

It does make the implementation slightly more complex, and maybe the existing implementations would only call the GenerateAsync method, without leveraging chunking or a similar approach.

**Comment by stephentoub** [comment]
@SteveSandersonMS, opinions on this?

**Comment by stephentoub** [comment]
@luisquintanilla, @SteveSandersonMS, do we want to do anything with this one, or just say it's up to consumers?

**Comment by SteveSandersonMS** [comment]
Personally I think we'd want to support streaming **if** it was inherent to the underlying generator (as it is for chat). But since it isn't inherent, it feels more like a pattern that consumers would apply themselves if they want it. Then it's up to the consumer to decide things like whether to parallelize the chunks.

So I'd vote for not layering on this concept ourselves when it's not inherent to the concept of embedding generation.

**Comment by stephentoub** [comment]
Ok, thanks. Closing this for now. Thanks, @azchohfi, for the suggestion.

**Comment by roji** [comment]
> Personally I think we'd want to support streaming if it was inherent to the underlying generator (as it is for chat). But since it isn't inherent, it feels more like a pattern that consumers would apply themselves if they want it. Then it's up to the consumer to decide things like whether to parallelize the chunks.

I noticed this point when going over the IEmbeddingGenerator API for MEVD, and would like to make sure we're doing the right thing here...

In general, the fact that the IEmbeddingGenerator API is batching (since it accepts an enumerable of values and returns a GeneratedEmbeddings collection) itself seems like a good reason to allow for streaming the results:
* For any underlying generator which does **not** support batching, the IEmbeddingGenerator implementation would be the one implementing fake-batching by simple calling a non-batching API on the underlying multiple times. At that point, allowing the results to be streamed provides them potentially must faster. I suspect this would be the case with most/all local embedding generators, no?
* It's true that at least some (maybe all) .NET embedding generator SDKs don't expose a streaming API (e.g. OpenAI's API returns a collection). However, underneath things are basically a big JSON array, which inherently **could** be streamed, returning earlier results before the entire JSON document has been delivered - it would be a pity if we blocked this possibility in our API even if popular cloud-service SDKs don't currently seem to support it (and someone who really cares about performance could go around them and simply implement an IEmbeddingGenerator via HttpClient, process the JSON etc.).
* For expensive embedding models, streaming could be quite important for response. I'm assuming that with multi-model this becomes even more important (e.g. generating embeddings for images, even videos...).
* I'm not sure there's a big downside to doing this; for single-embedding use, we already have an extension method sugar - that would continue working exactly as today. Users of the batching API could simply compose ToListAsync() to get the list. This is very easy in .NET thanks to the new IAsyncEnumerable operators, but would require System.Linq.Async in other .NET versions - if we want we can introduce another extension method to help users with that scenario.
* However:
  * We can’t directly return IAsyncEnumerable, since GeneratedEmbeddings has additional metadata covering the entire batch (UsageDetails, AdditionalProperties) 
  * We could return a wrapping type with the metadata, which would expose an IAsyncEnumerable over the result embeddings. This is the pattern used in MEVD for vector search (see [VectorSearchResult](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Connectors/VectorData.Abstractions/VectorSearch/VectorSearchResults.cs)).
  * One issue with this pattern, is that it’s unclear when the metadata would be populated – I’m assuming in at least some services, the usage information might come after the results, so the IAsyncEnumerable would have to be consumed before the values could be populated; maybe we can live with this shortcoming. Note that this affects MEVD’s VectorSearchResult as well.

/cc @westey-m who has more knowledge with actual embedding generator services, what are your thoughts on the above?
