### ISSUE TITLE
[API Proposal]: Microsoft.Extensions.AI  - Use structured output with function calling

### ISSUE THREAD

**Issue by sylvain-guillet** [dotnet/extensions#5612]
### Background and motivation

Allow developers to use structured output with function calling : https://platform.openai.com/docs/guides/function-calling#function-calling-with-structured-outputs

Open AI says:

"By default, when you use function calling, the API will offer best-effort matching for your parameters, which means that occasionally the model may miss parameters or get their types wrong when using complicated schemas.

[Structured Outputs](https://platform.openai.com/docs/guides/structured-outputs) is a feature that ensures model outputs for function calls will exactly match your supplied schema.

Structured Outputs for function calling can be enabled with a single parameter, just by supplying strict: true"

### API Proposal

```csharp
public static AIFunction Create(
      Delegate method,
bool isStrict,
      string? name = null,
      string? description = null,
      JsonSerializerOptions? serializerOptions = null)
    {
      ...
    }

```

### API Usage

AIFunctionFactory.Create(Tools.TimeTools.ConvertDateTime,strict:true), //set strict to true

**Comment by stephentoub** [comment]
>bool isStrict,

What's the benefit of having this rather than just having the underlying implementation always set the equivalent of "isStrict=true" if it's available? When would you as a developer want "isStrict=false"?

That said, note that the OpenAIChatClient already supports this. You can set a "Strict" key into the AIFunction's properties dictionary, and it'll use that to override the default from the underlying implementation:
https://github.com/dotnet/extensions/blob/c86b7ead537a3534eb7fbc748384417b6a552bf0/src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIChatClient.cs#L487-L490

**Comment by sylvain-guillet** [comment]
But it seems the generated schema is not compliant with the "strict" option. To reproduce the case, I 've defined my function ti be strict like this : 
```
var myfunction = AIFunctionFactory.Create(Tools.MyFunction, new AIFunctionFactoryCreateOptions { AdditionalProperties = new Dictionary<string, object>() { { "Strict", true } } });
```
My function has a double parameter and GPT says me " pattern used in your property is not supported" this is because a pattern is added in the schema when number is decimal, double or float. Secondary I've replaced my double parameter with an integer to avoid the add of "pattern" but now I've a new error returned by GPT : "AdditionalProperties is missing and must be set to false". It seems the schema generation is not well handled when strict is used.

**Comment by stephentoub** [comment]
cc: @eiriktsarpalis

**Comment by eiriktsarpalis** [comment]
I believe this happens because of the restrictions OpenAI imposes on accepted schemas:

https://platform.openai.com/docs/guides/structured-outputs#supported-schemas

The built-in schema generator does not mark all properties as `required` nor does it always introduce `additionalProperties : false`. We should update the AI schema generator so that it refines generated documents to the subset supported by OpenAI specifically. 

In the interim, you can make the schema generator include `additionalProperties : false` today by annotating your type with `[JsonUnmappedMemberHandling(JsonUnmappedMemberHandling.Disallow)]`.
