### ISSUE TITLE
Redis Timing out exceptions

### ISSUE THREAD

**Issue by chaheti29** [dotnet/extensions#573]
We are getting continuous Redis Timeout exceptions. 
Timeout awaiting response (5562ms elapsed, timeout is 5000ms), inst: 0, qs: 39, in: 895, serverEndpoint: Unspecified/redistestwe.redis.cache.windows.net:6380, mgr: 10 of 10 available, clientName: RD2818789816DC, IOCP: (Busy=52,Free=948,Min=2,Max=1000), WORKER: (Busy=4,Free=8187,Min=2,Max=8191), v: 2.0.513.63329 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts) 

**One Observation:**
When I use Async methods(GetStringAsync and SetStringAsync) i see this issues. With Sync methods it doesnt happen.

Attached is my code.
[RedisTest.zip](https://github.com/aspnet/Extensions/files/2624887/RedisTest.zip)

**Comment by anurse** [comment]
Closing as this issue got stale (apologies for the delayed response). Feel free to open a new issue if you're still experience this problem.

---

##### Note: Inactive closed issues are locked after 30 days since we don't triage closed issues and new comments tend to be lost. Feel free to post a new issue if this issue is locked and you have questions. See [our issue management policies](https://github.com/dotnet/aspnetcore/blob/master/docs/IssueManagementPolicies.md) for more details.
