### ISSUE TITLE
Add doc comments to public APIs

### ISSUE THREAD

**Issue by halter73** [dotnet/extensions#663]
This repo currently has a lot of public APIs without any doc comments.

There's already an issue (#610) about adding doc comments for `EventId`.

There's also a pretty old PR (#529) to add doc comments to console logger types. Having doc comments to indicate things like the default value of `ConsoleLoggerOptions.IncludeScopes` could certainly be useful. There are other console logging types that don't have doc comments like `IConsoleLoggerSettings`, but I haven't created an exhaustive list.

None of the (extension) methods on ILoggingBuilder (i.e. AddFilter, AddProvider, ClearProviders, SetMinimuLevel) have doc comments.

I Think it would be particularly useful to note in the SetMinimumLevel doc comments that the default LogLevel is Information meaning that Trace and Debug logs will be ignored.  I think this should be noted on any API where a minimum level can be set.

**Comment by breyed** [comment]
There are many cases of non-obvious semantics with no documentation. For example, what does [StringValues.Implicit(StringValues to String)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.primitives.stringvalues.op_implicit?view=dotnet-plat-ext-3.1#Microsoft_Extensions_Primitives_StringValues_op_Implicit_System_String__Microsoft_Extensions_Primitives_StringValues) return `Count` is 0?

If .NET's selling point is developer productivity, having to search out source code to determine behavior undermines the goal. Likewise, if long-term stability is a selling point, it's diminished too, since every use of the API is by definition undocumented behavior. Who can tell what is and is not intended to stay constant between versions?

**Comment by breyed** [comment]
I just noticed that the [source](https://github.com/dotnet/extensions/blob/master/src/Primitives/src/StringValues.cs) has XML comments. However, they're not coming through to the API website or IntelliSense. Is the build pipeline broken?

**Comment by anurse** [comment]
These will be handled by the docs process in dotnet/runtime now, since the packages have moved there and the XML docs are handled in dotnet/dotnet-api-docs
