### ISSUE TITLE
Bind is ordered my Dictionary

### ISSUE THREAD

**Issue by joniltonsilva** [dotnet/extensions#776]
Hi,

Is that possible to add an option without ordering at this method?

```
 public IEnumerable<string> GetChildKeys(
            IEnumerable<string> earlierKeys,
            string parentPath)
        {
            var section = parentPath == null ? _config : _config.GetSection(parentPath);
            var children = section.GetChildren();
            var keys = new List<string>();
            keys.AddRange(children.Select(c => c.Key));
            return keys.Concat(earlierKeys);
                .OrderBy(k => k, ConfigurationKeyComparer.Instance);
        }
```

I'm trying to bind IOption<MyClass> into Dictionary property, but the dicitonary is getting ordered, is there a way make it without ordering?

Example: 

![json](https://user-images.githubusercontent.com/13085990/41481854-ef0ebd4a-70a9-11e8-9101-a5f07e99720d.JPG)
![class](https://user-images.githubusercontent.com/13085990/41481858-f3374ffe-70a9-11e8-8116-7a3cf77b357f.JPG)
![configure](https://user-images.githubusercontent.com/13085990/41481860-f616d410-70a9-11e8-84b0-48f414a15b00.JPG)

The result with **Dictionary Ordered**

![watch](https://user-images.githubusercontent.com/13085990/41481866-faf21a4e-70a9-11e8-8844-4fa7ca46deb2.JPG)

**Comment by anurse** [comment]
> Is that possible to add an option without ordering at this method?

What's the scenario that *requires* differently-ordered results? Are you trying to preserve declaration order? In general, dictionaries/maps/hashtables _do not_ preserve ordering. Similarly, the JSON spec itself states (**emphases** added):

> An object is an **unordered** set of name/value pairs.
>
> https://www.json.org/json-en.html

This means that declaration order should not be relied upon. If you want ordering to be preserved, you should use an array.

Closing as we don't plan to change this ordering at this time.

---

##### Note: Inactive closed issues are locked after 30 days since we don't triage closed issues and new comments tend to be lost. Feel free to post a new issue if this issue is locked and you have questions. See [our issue management policies](https://github.com/dotnet/aspnetcore/blob/master/docs/IssueManagementPolicies.md) for more details.
