### ISSUE TITLE
Environment variables not found

### ISSUE THREAD

**Issue by steveoh** [dotnet/extensions#781]
I am working with vs for mac on the beta channel and a dotnet core mvc application. I run an iterm2 console with zsh and a `~/.zshrc` file. I have a few machine level environment variables being exported from that rc file. eg:

```shell
export WEBAPI__DATABASE__PASSWORD="what password"¬
export WEBAPI__DATABASE__PEPPER="spicy"¬
```

I have set those values, restarted, yada yada, everything that should make them visible to vs for mac and the dotnet application. The [use multiple environments](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-2.1#macos) section on mac mentions editing a `.bashrc` and `.bash_profile` so I would assume my `.zshrc` file would function equivalently. 

I read through the mono [Environment](https://github.com/mono/mono/blob/master/mcs/class/corlib/System/Environment.cs) file but nothing stood out. I do not understand why these values are not picked up by the [EnvironmentVariablesConfigurationProvider](https://github.com/aspnet/Configuration/blob/master/src/Config.EnvironmentVariables/EnvironmentVariablesConfigurationProvider.cs) or what I need to do differently to make them get picked up. 

The only solution that works for now is to add them to the project options.

![image](https://user-images.githubusercontent.com/325813/43728693-1beb722c-9963-11e8-9351-a84913fafc70.png)

**Comment by anurse** [comment]
@steveoh Apologies for the delay, we're going through some backlog grooming now and trying to pick up these lost issues. If you're no longer hitting this issue or have otherwise moved on, no worries!

Can you check if the environment variables are present by using `Environment.GetEnvironmentVariable` in your application? If the variable is not present using that API then this is probably a VS for Mac issue and should be reported through their feedback process. They may be clearing out other environment variables not defined in your Run configuration.

If the variable **is** present using `GetEnvironmentVariable` but not showing up in the config, then it would be an issue in the config provider and we can investigate further.

**Comment by steveoh** [comment]
I'll have to see what I did in the mean time and test this out for ya.

**Comment by anurse** [comment]
Closing this as we haven't heard from you. If you or anyone else are still encountering an issue like this, feel free to file a new issue on [dotnet/runtime](https://github.com/dotnet/runtime) (where this code now lives) and we'll investigate!
