### ISSUE TITLE
Being able to use the EnvironmentVariablesConfigurationProvider without removing the prefix

### ISSUE THREAD

**Issue by TrymBeast** [dotnet/extensions#922]
I would like to be able to configure the EnvironmentVariablesConfigurationProvider to filter environment variables with a prefix, but to not remove the prefix.

The solution for this I think it's pretty straight forward, just adding a bool to indicate to remove the prefix or not in EnvironmentVariablesConfigurationProvider, and a new extension method, keeping the remove prefix behavior by default.

**Comment by poke** [comment]
Using environment variables as a source for configuration is usually used as a way to explicitly overwrite configuration without having to specifiy possibly secret values within configuraiton files. As such, it is usually that the configuration keys (or paths) are already defined by an existing configuration structure.

As such, it does not really make that much sense to keep the prefixes of prefixed environment variables. It sounds more like what you actually want to do is to just read out environment variables (instead of trying to actually rely on a proper configuration setup). You could just use [`Environment.GetEnvironmentVariable`](https://docs.microsoft.com/en-us/dotnet/api/system.environment.getenvironmentvariable?view=netcore-2.1) for that.

Otherwise, if you do actually want to use configuration, you could also just load all environment variables. While you will get values you don’t need, you will also get all the environment variables with that prefix included.

**Comment by TrymBeast** [comment]
Hello @poke,

I am using environment variables to override values from configuration files, this will be used especially because of Docker.

But what I am doing is actually more complex than that, instead of having just one configuration file I have many, when I would have 10 different sections in one configuration file I now have 10 different files, this way I can inject an IConfiguration that is specific to some feature.

My initial idea was to actually don't use any prefix in this files, but because of Serilog that only uses an IConfigurationSection I had to change my strategy and support both with or without the prefix, for this I had to implement an wrapper for the actual IConfiguration to include the prefix when used without it.

But now I was left with this issue of the environment variables, I can always have my own implementation of it, I already have that to overcome the issue and move on, but if this was an out of the box feature it would have been better.

**Comment by anurse** [comment]
@TrymBeast we're coming back to this after letting some issues go idle for a bit. Can you provide a concrete example of the prefixes you're using and how you want them to map in to the config system? I mostly agree with @poke 's description here, that leaving the prefix seems counter to the main goal of the provider.

**Comment by anurse** [comment]
Closing this as we haven't heard from you.
